### ISSUE TITLE
Can't open terminal in Che deployed with Che minishift addon

### ISSUE THREAD

**Issue by jarifibrahim** [eclipse-che/che#12451]
### Description
 

I'm running che on minishift via the minishift addon. I'm using the che-server:nightly docker image.
I have created a workspace using the following devfile
```yaml
---
specVersion: 0.0.1
name: petclinic-dev-environment
projects:
  - name: petclinic
    source:
      type: git
      location: 'git@github.com:spring-projects/spring-petclinic.git'
tools:
  - name: theia-ide
    type: cheEditor
    id: org.eclipse.che.editor.theia:1.0.0
  - name: terminal
    type: chePlugin
    id: che-machine-exec-plugin:0.0.1
commands:
  - name: hello
    actions:
      - type: exec
        tool: theia-ide
        command: echo Hello
        workdir: /projects/spring-petclinic
```

The workspace was created but I couldn't start a terminal. The che pod on minishift had the following error
```
[GIN] 2019/01/16 - 14:08:19 | 200 |    3.161257ms |    192.168.42.1 | GET      /connect
Unable to create machine exec. Cause:  pods is forbidden: User "system:serviceaccount:mini-che:default" cannot list pods in the namespace "mini-che": no RBAC policy matched
```
### Reproduction Steps
1. Start che in minishift using the addon.
2. Replace image with `che-server:nightly`
3. Create a workspace via post request to `api/devfile` with payload
```yaml
---
specVersion: 0.0.1
name: petclinic-dev-environment
projects:
  - name: petclinic
    source:
      type: git
      location: 'git@github.com:spring-projects/spring-petclinic.git'
tools:
  - name: theia-ide
    type: cheEditor
    id: org.eclipse.che.editor.theia:1.0.0
  - name: terminal
    type: chePlugin
    id: che-machine-exec-plugin:0.0.1
commands:
  - name: hello
    actions:
      - type: exec
        tool: theia-ide
        command: echo Hello
        workdir: /projects/spring-petclinic
```

4. Start the newly created workspace and try to open a new terminal.

**Comment by jarifibrahim** [comment]
> The `che` minishift addon should be updated to create a workspace service account. See the corresponding changes in Che OpenShift Deployment https://github.com/eclipse/che/pull/11178/files#diff-4c117f11c7596b935e7f15cc8b857379R10

@sleshchenko The minishift addon looks up-to-date to me https://github.com/minishift/minishift/blob/master/addons/che/templates/che-workspace-service-account.yaml

Am I missing something?

**Comment by jarifibrahim** [comment]
> @jarifibrahim You're right. Thanks for notifying. Then need to debug such Che instance. There may be some misconfiguration in Che Server Config Map.

What information do you need for debugging? I can help with that.

**Comment by sleshchenko** [comment]
> What information do you need for debugging? I can help with that.

@jarifibrahim Thanks. I can easily set up my own `minishift` installation.
But this issue should be prioritized to be taken in the sprint of `che-platform` or `che-osio` team.

**Comment by l0rd** [comment]
@jarifibrahim can you please provide your minishift version?

**Comment by l0rd** [comment]
@jarifibrahim I just checked on minishift and I can create a workspace using your devfile and I don't have issues with the terminal. The serviceaccount problem @sleshchenko is mentioning was fixed [a couple of months ago](https://github.com/minishift/minishift/pull/3011) (in minishift version v1.28).

**Comment by jarifibrahim** [comment]
> @jarifibrahim I just checked on minishift and I can create a workspace using your devfile and I don't have issues with the terminal. The serviceaccount problem @sleshchenko is mentioning was fixed [a couple of months ago](https://github.com/minishift/minishift/pull/3011) (in minishift version v1.28).

Thanks @l0rd . I was using minishift v1.27.0.
I've updated my minishift to 1.30 but I still see the same error
```

  | Use kubernetes implementation
-- | --
  | [GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.
  | [GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
  | - using env:	export GIN_MODE=release
  | - using code:	gin.SetMode(gin.ReleaseMode)
  | [GIN-debug] GET    /connect                  --> main.main.func1 (3 handlers)
  | [GIN-debug] GET    /attach/:id               --> main.main.func2 (3 handlers)
  | ⇩ Registered RPCRoutes:
  | Json-rpc MachineExec Routes:
  | ✓ create
  | ✓ check
  | ✓ resize
  | [GIN-debug] Listening and serving HTTP on :4444
  | [GIN] 2019/01/24 - 09:37:56 \| 200 \|     989.137µs \|    192.168.42.1 \| GET      /connect
  | Unable to create machine exec. Cause:  pods is forbidden: User "system:serviceaccount:mini-che:default" cannot list pods in the namespace "mini-che": no RBAC policy matched
  | Unable to create machine exec. Cause:  pods is forbidden: User "system:serviceaccount:mini-che:default" cannot list pods in the namespace "mini-che": no RBAC policy matched
  | Unable to create machine exec. Cause:  pods is forbidden: User "system:serviceaccount:mini-che:default" cannot list pods in the namespace "mini-che": no RBAC policy matched

```

@l0rd Did you create the namespace via `system:admin` account? I'm running everything via the `developer` account.

**Comment by l0rd** [comment]
@jarifibrahim no I am running everything as `developer`. Note that when you update minishift addons will be updated only when you restart minishift and you need to confirm that you want to update them:

```
Do you want to update the default add-ons? [y/N]: y
Default add-ons will be updated the next time you run any 'minishift' command.
```

And if your addon is already enabled (so Che was already installed) you may need to clean up the old install and re-install it:

```
minishift addons remove che
# make sure that all resources are deleted from 
# namespace mini-che with `oc get all -n mini-che`
# before running the next command
minishift addons apply che
```

**Comment by jarifibrahim** [comment]
> @jarifibrahim no I am running everything as `developer`. Note that when you update minishift addons will be updated only when you restart minishift and you need to confirm that you want to update them:
> 
> ```
> Do you want to update the default add-ons? [y/N]: y
> Default add-ons will be updated the next time you run any 'minishift' command.
> ```
> And if your addon is already enabled (so Che was already installed) you may need to clean up the old install and re-install it:
> 
> ```
> minishift addons remove che
> # make sure that all resources are deleted from 
> # namespace mini-che with `oc get all -n mini-che`
> # before running the next command
> minishift addons apply che
> ```

No luck @l0rd. I still see the forbidden error. I'll ask someone else to give this a try. This could be my machine specific error :)

**Comment by l0rd** [comment]
@jarifibrahim when anything else works I usually `minishift stop && minishift delete && rm -rf ~/.minishift/ && minishift start --memory 8GB && minishift addons apply che` but ⚠️  that reset your current minishift installation :-)

**Comment by jarifibrahim** [comment]
@l0rd That work!! Thank you so much. 

![](https://media1.tenor.com/images/9dac8192b4b475477730e2e00bbcabef/tenor.gif?itemid=5027655)


Closing the issue as it doesn't exist.

**Comment by sbose78** [comment]
Worked for me too, and even on a fresh installation I had to reset the minishift installation!
