### ISSUE TITLE
Plugin doesn't launch after adding it to the workspace

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#12904]
**Related cypress test:**
 - "WorkspaceCreationAndLanguageServerInitialization.spec.ts"

### Reproduction Steps
 - Deploy Che by using "chectl"
 - Go to "New Workspace" page
 - Select "Che 7" stack
 - Add "web-java-spring" project
 - Enable "Language Support for Java(TM)" plugin
 - Click on "Create and Open" button
 - Wait until workspace is started
 - Go to project tree and open "java" file
 - Pay attention that Language Server initialization doesn't start

**Expected behavior:**
After java file opened, language server initialization started

**Observed behavior:**
After java file opened, language server initialization is not started

**Sidecar logs:**
```

Plugins Endpoints are  [ 'ws://zrixdreasj:5889' ]
Plugins Mapping Endpoints are  Map { 'redhat_java' =&gt; 'ws://zrixdreasj:5889' }
Starting the deployer with the list of resolvers [ LocalDirectoryPluginDeployerResolver {},
  GithubPluginDeployerResolver { unpackedFolder: '/tmp/github-remote' },
  HttpPluginDeployerResolver { unpackedFolder: '/tmp/http-remote' },
  VsCodePluginDeployerResolver { unpackedFolder: '/tmp/vscode-extension-marketplace' } ]
Theia Endpoint 1/pid listening on port 5889
Found the list of default plugins ID on env: undefined
Found the list of plugins ID on env: undefined
Found the list of default plugins ID from CLI: undefined
```

**OS and version:**    
Che 7.0.0-beta-2.0-SNAPSHOT

**Comment by Ohrimenko1988** [comment]
Unskip test methods in the "WorkspaceCreationAndLanguageServerInitialization.spec.ts" cypress test after resolving this issue.

**Comment by l0rd** [comment]
@tsmaeder is your team working to fix this issue?

**Comment by tsmaeder** [comment]
@l0rd no we're not. The info seems to indicate this is a general problem with the plugin mechanism.

**Comment by tsmaeder** [comment]
Maybe this is related? https://github.com/theia-ide/theia/issues/3970

**Comment by benoitf** [comment]
I gave a look, on my side I've the container of vscode-java with the sidecar having 128MB of memory

che-theia:next, and vscode java plug-in from registry

thus, launching the JDT.LS process is being killed
```
 # /usr/lib/jvm/default-jvm/bin/java -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -noverify -X
mx128m -XX:+UseG1GC -XX:+UseStringDeduplication -jar /plugins/org.eclipse.che.vscode-redhat.java.0.38.0.redhat_java/extension/server/plugins/org.eclipse.equinox.launcher_1.5.200.v20180922-1751.jar -configuration /plugins/org.eclipse.che.vscode-redhat.java.
0.38.0.redhat_java/extension/server/config_linux -data /Users/benoitf/.theia/workspace-storage/c2731c0788339744944161fd8afb74dd/redhat.java/jdt_ws
Killed

```

**Comment by tsmaeder** [comment]
Where did you get that info from?

**Comment by benoitf** [comment]
I debugged vscode-java to know what was the command line it was launching and figure out that when trying it manually it's being killed as there is not enough memory

**Comment by tsmaeder** [comment]
But shouldn't we at least get some log output from the plugin host process?

**Comment by benoitf** [comment]
host process is not launching the java process, it's vscode-java extension with lsp library (I don't know how they're handling the crash of the process)

> How do you know that is really the problem and not something else?

When I give more memory I see the plug-in being working when I start my workspace
![image](https://user-images.githubusercontent.com/436777/54762595-b4dd0d80-4bf4-11e9-8243-707f3f6f93be.png)

**Comment by benoitf** [comment]
I added in my workspace configuration:
```
 "attributes": {
    ...
    "sidecar.org.eclipse.che.vscode-redhat.java.memory_limit": "1024Mi",
    ...
  },
```

**Comment by benoitf** [comment]
![image](https://user-images.githubusercontent.com/436777/54763860-025a7a00-4bf7-11e9-8a78-18a53ff76ea4.png)

**Comment by l0rd** [comment]
The Java stack that I am testing [allocates 1GB or RAM](https://github.com/eclipse/che/blob/7ce84f398875c7e496b5b6096ed1fa66aae84504/ide/che-core-ide-stacks/src/main/resources/stacks.json#L812). But the extension cannot load anyway.

I have tried with 2GB, same result. I have also tried with https://github.com/eclipse/che-theia/pull/124 but it's still not working.

Can it be related to the fact that we use [v0.38.0](https://github.com/eclipse/che-plugin-registry/blob/master/plugins/org.eclipse.che.vscode-redhat.java/0.38.0/meta.yaml) of the extension whereas current version [is v0.40.0](https://github.com/redhat-developer/vscode-java/releases)?

**Comment by tsmaeder** [comment]
Ok, this has nothing to do with the Java plugin per so, but affects all plugins trying to write to the "storagePath" given to them by the plugin API in the "PluginContext" object:

Caused by: java.lang.IllegalStateException: The platform metadata area could not be written: /home/theia/.theia/workspace-storage/be0a81bfde25dc291c35808bdaf5f836/redhat.java/jdt_ws/.metadata.  By default the platform writes its content
under the current working directory when the platform is launched.  Use the -data parameter to
specify a different content area for the platform.
        at org.eclipse.core.internal.runtime.DataArea.assertLocationInitialized(DataArea.java:73)
        at org.eclipse.core.internal.runtime.DataArea.getStateLocation(DataArea.java:141)
        at org.eclipse.core.internal.preferences.InstancePreferences.getBaseLocation(InstancePreferences.java:47)

**Comment by tsmaeder** [comment]
Turns out "/home/theia" in the sidecar is owned by root and only writeable by the owner. It seems the theia plugin host is not run as "root" in minishift.

**Comment by tsmaeder** [comment]
I asked how we can have a writeable folder in a container on openshift and was pointed to this code: https://github.com/eclipse/che-dockerfiles/blob/master/recipes/stack-base/centos/Dockerfile#L51-L61

This would mean anyone wanting to make a base image for a Che 7 plugin would have to include that code. Seems like a big ask.

**Comment by benoitf** [comment]
@l0rd : you were testing on minikube or minishift ?

**Comment by garagatyi** [comment]
@tsmaeder all the images should be designed to run without root/sudo on Openshift. It is a big as, yes. But it is needed in some cloud environments.

**Comment by l0rd** [comment]
Ok cool so it looks like we have found the problem. 

@benoitf I was testing on minishift. 

Yes the sidecar images, given that they are own by us, should work fine on OpenShift and Kubernetes. We can do the [trick mentioned](https://github.com/eclipse/che-dockerfiles/blob/master/recipes/stack-base/centos/Dockerfile#L51-L61) by @tsmaeder, but we can also mount a volume in `/home/theia` and that would work as well.

**Comment by tsmaeder** [comment]
> all the images should be designed to run without root/sudo on Openshift

I'm not asking for sudo or root, just a writeable folder. I just can't believe we're the first people to want to write to a file in Openshift.

**Comment by garagatyi** [comment]
It is not that Openshift doesn't allow you to write but image wasn't designed to be properly used in an environment where user is not root.
Since on image construction stage user was root and at runtime it is not root it makes it impossible to write to the folder. It can also a problem in some non-root cases. 
Dockerfile author has to design it in a way that allows proper usage with the Openshift.

**Comment by benoitf** [comment]
I will handle the update of the docker image

**Comment by tsmaeder** [comment]
We'll need to document the requirement (for a writeable home directory) in our developer docs.

**Comment by tsmaeder** [comment]
https://github.com/eclipse/che-theia/pull/130

**Comment by benoitf** [comment]
I was able to use java with 2GB for sidecar on minishift (only 1GB on minikube)

here is my workspace config:
```json
{
  "environments": {
    "default": {
      "recipe": {
        "contentType": "application/x-yaml",
        "type": "kubernetes",
        "content": "kind: List\nitems:\n - \n  apiVersion: v1\n  kind: Pod\n  metadata:\n   name: ws\n  spec:\n   containers:\n    - \n     image: 'eclipse/che-dev:7.0.0-beta-2.0'\n     name: dev\n     resources:\n      limits:\n       memory: 512Mi\n"
      },
      "machines": {
        "ws/dev": {
          "env": {},
          "servers": {},
          "volumes": {
            "projects": {
              "path": "/projects"
            }
          },
          "installers": [],
          "attributes": {
            "memoryLimitBytes": "536870912"
          }
        }
      }
    }
  },
  "defaultEnv": "default",
  "projects": [],
  "commands": [],
  "name": "wksp-gy4h",
  "attributes": {
    "plugins": "che-machine-exec-plugin:0.0.1,org.eclipse.che.vscode-redhat.java:0.38.0",
    "sidecar.org.eclipse.che.vscode-redhat.java.memory_limit": "2048Mi",
    "editor": "org.eclipse.che.editor.theia:next"
  },
  "links": []
}
```

![image](https://user-images.githubusercontent.com/436777/54914469-51552780-4ef5-11e9-843a-16ea39429c8d.png)

**Comment by tsmaeder** [comment]
@benoitf did you try reducing the amount of -Xmx for jdt.ls in the plugin settings for vscode-java?

**Comment by benoitf** [comment]
@tsmaeder no, it's using 1G for Xmx so I can try with 1200MB for example
```
/usr/lib/jvm/default-jvm/bin/java -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication -jar /plugins/org.eclipse.che.vscode-redhat.java.0.38.0.redhat_java/extension/server/plugins/org.eclipse.equinox.launcher_1.5.200.v20180922-1751.jar -configuration /plugins/org.eclipse.che.vscode-redhat.java.0.38.0.redhat_java/extension/server/config_linux -data /home/theia/.theia/workspace-storage/be0a81bfde25dc291c35808bdaf5f836/redhat.java/jdt_ws

```

**Comment by benoitf** [comment]
with `1536Mi` it is working on my side as well.

**Comment by tsmaeder** [comment]
1G should be enough for modest project sizes. Are you sure we're getting OOM from the JVM and that we're not missing native memory? In that case, we can reduce the -Xmx for the jdt.ls process in the settings.

**Comment by benoitf** [comment]
I used pom.xml from https://quarkus.io/guides/getting-started-guide (and just created dummy .java file) so I would say it's kind of one file project size.
About memory I didn't check if container was restarted or not but with 1Gi the java process is no longer there after some time (either native memory reached or java process is killed)

**Comment by tsmaeder** [comment]
1G should be enough for modest project sizes. Are you sure we're getting OOM from the JVM and that we're not missing native memory? In that case, we can reduce the -Xmx for the jdt.ls process in the settings.

**Comment by gorkem** [comment]
@tsmaeder Should't we be setting the memory for jdt.ls relative to the available memory on the container? User sets the memory allocated for the container and we determine the best way to utilize that.

**Comment by tsmaeder** [comment]
@gorkem you'd have to address this question to Fred, since we're reusing the vanilla vscode-java plugin. But yes, they could be smarter. 
That said, we _will_ have minimum requirements for Che 7 plugins. Currently, we cannot set them, unfortunately neither in the dashboard nor in the Che 7 plugin descriptor.

**Comment by l0rd** [comment]
For the record I have created #12992 to address the memory issue.

**Comment by l0rd** [comment]
@Ohrimenko1988 it looks like this one has been fixed. Can you please verify and close it?

**Comment by garagatyi** [comment]
@Ohrimenko1988 ^ Please take a look

**Comment by Ohrimenko1988** [comment]
@garagatyi 
Bug still reproduces. I checked it on my local kubernetes che deployed by chectl
workspace config

![Screenshot from 2019-04-19 09-55-45](https://user-images.githubusercontent.com/22724619/56411724-5f932b00-628a-11e9-994b-d0ad102b1e12.png)

```
{
  "defaultEnv": "default",
  "environments": {
    "default": {
      "machines": {
        "ws/dev": {
          "attributes": {
            "memoryLimitBytes": "536870912"
          },
          "servers": {},
          "volumes": {
            "projects": {
              "path": "/projects"
            }
          },
          "installers": [],
          "env": {}
        }
      },
      "recipe": {
        "type": "kubernetes",
        "content": "kind: List\nitems:\n - \n  apiVersion: v1\n  kind: Pod\n  metadata:\n   name: ws\n  spec:\n   containers:\n    - \n     image: 'eclipse/che-dev:nightly'\n     name: dev\n     resources:\n      limits:\n       memory: 512Mi\n",
        "contentType": "application/x-yaml"
      }
    }
  },
  "projects": [
    {
      "links": [],
      "name": "console-java-simple",
      "attributes": {
        "language": [
          "java"
        ]
      },
      "type": "maven",
      "source": {
        "location": "https://github.com/che-samples/console-java-simple.git",
        "type": "git",
        "parameters": {
          "branch": "master"
        }
      },
      "path": "/console-java-simple",
      "description": "A hello world Java application.",
      "mixins": [],
      "problems": []
    }
  ],
  "name": "wksp-o6xs",
  "attributes": {
    "editor": "org.eclipse.che.editor.theia:1.0.0",
    "plugins": "che-machine-exec-plugin:0.0.1,org.eclipse.che.vscode-redhat.java:0.38.0"
  },
  "commands": [
    {
      "commandLine": "mvn -Duser.home=${HOME} -f ${CHE_PROJECTS_ROOT}/console-java-simple clean install",
      "name": "console-java-simple:maven build",
      "attributes": {
        "goal": "Build",
        "previewUrl": ""
      },
      "type": "mvn"
    },
    {
      "commandLine": "mvn -Duser.home=${HOME} -f ${CHE_PROJECTS_ROOT}/console-java-simple clean install \njava -jar ${CHE_PROJECTS_ROOT}/console-java-simple/target/*.jar",
      "name": "console-java-simple:maven build and run",
      "attributes": {
        "goal": "Run",
        "previewUrl": ""
      },
      "type": "mvn"
    },
    {
      "commandLine": "cd ${CHE_PROJECTS_ROOT}/console-java-simple; gradle build",
      "name": "console-java-simple:gradle build",
      "attributes": {
        "goal": "Build",
        "previewUrl": ""
      },
      "type": "gralde"
    },
    {
      "commandLine": "cd ${CHE_PROJECTS_ROOT}/console-java-simple; gradle run",
      "name": "console-java-simple:gradle run",
      "attributes": {
        "goal": "Run",
        "previewUrl": ""
      },
      "type": "gradle"
    }
  ],
  "links": []
}
```

**Comment by l0rd** [comment]
@Ohrimenko1988 can we close this one?
