### ISSUE TITLE
Even if the project is deleted from a VS Code workspace, it's back when the Che workspace is re-started

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#13621]
### Description
Deleting a project, refreshing the workspace, the project is back.

![delete-project](https://user-images.githubusercontent.com/1636769/59962767-e910e480-94e9-11e9-8a28-12f03836ee6c.gif)

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by sunix** [comment]
@olexii4 you fix it i recommand you update these test with devfile: https://github.com/eclipse/che-theia/blob/master/plugins/factory-plugin/tests/projects.spec.ts#L164-L275

**Comment by olexii4** [comment]
@sunix  Ok
I tested it with the next version and standard devfile.
I depend on the work of a language server.

delete a project
https://youtu.be/FdHwE8zqrQk

Impossible to delete a project
https://youtu.be/-ymSH71kwbM

**Comment by sunix** [comment]
@olexii4 I have just reproduced the problem with 

```yaml
metadata:
  name: che7-readme-update-e
projects:
  - name: che
    source:
      location: 'https://github.com/eclipse/che'
      type: git
  - name: web-rails-simple
    source:
      location: 'https://github.com/che-samples/web-rails-simple.git'
      type: git
components:
  - mountSources: true
    command:
      - tail
    args:
      - '-f'
      - /dev/null
    memoryLimit: 512M
    type: dockerimage
    image: sunix/git-devtools
    alias: sunix-git-devtools
apiVersion: 1.0.0
```

try to check only the devfile tab. and refresh before and after.

**Comment by olexii4** [comment]
The original issue has two problems.  One is a synchronization of the existing projects(fixed in PR).
The other is a result of a language server work and we can still reproduce it https://youtu.be/voqsE7LCVlA

**Comment by sunix** [comment]
For this issue we had 2 root causes:
- Deleting a project would remove it from the devfile as well, but that was broken. Fixed by https://github.com/eclipse/che-theia/pull/334 and https://github.com/eclipse/che-theia/pull/340
- Deleting a project can not get rid of somefile that are being used by a language server. The language server seems to be still `holding` the files. @tsmaeder could your team investigate that problem and see if we could do something ?

**Comment by olexii4** [comment]
@tsmaeder  @slemeur 
The original issue has two problems.  One is a synchronization of the existing projects(fixed in PRs).
The other is a result of a language server work.  And we can still reproduce it
https://youtu.be/voqsE7LCVlA

@tsmaeder Is it a normal behavior of LS(language server)? WDYT?

@slemeur  Could we close this issue as a fixed one?

**Comment by tsmaeder** [comment]
@olexii4 yes, when a build is running, for example, class files are produced, this is normal behaviour.

**Comment by tsmaeder** [comment]
Btw: I can reproduce the behaviour with VS Code: the /bin folder remains after I delete the project from the file explorer. Repeating the delete gets rid of the project eventually.

**Comment by tsmaeder** [comment]
Strike that...the project is back again.

**Comment by tsmaeder** [comment]
Btw: if we move to mounting projects as workspace roots, we can solve this one by first removing the workspace root and then deleting the project.

**Comment by slemeur** [comment]
@tsmaeder: What do you think it the expected behavior by the end-user?

**Comment by sunix** [comment]
@tsmaeder If you plan to fix that, could to explain what is your plan ?

This is the responsibility of the language server: files are being deleted and it has to kill the running process.

**Comment by l0rd** [comment]
Added label `in-progress` since I believe that what Thomas is working on should fix this issue.

**Comment by slemeur** [comment]
@tsmaeder : Can you provide an update on this?

**Comment by tsmaeder** [comment]
Using multi-root workspaces should mitigate this (at least being able to eventually delete the project). However, it is _VERY_ slow going. Wasting time on our self-hosting process.
