### ISSUE TITLE
Give more flexibility on where devfile registry can served up

### ISSUE THREAD

**Issue by makandre** [eclipse-che/che#13634]
### Description
 

I would like to make devfiles I have on GitHub show up in Che dashboard when creating a workspace.

I learned that I can configure Che's devfile registry by changing the `che.workspace.devfile_registry_url` property.

It would be great if I can change it so the devfiles can be served up directly from GitHub (e.g. set `che.workspace.devfile_registry_url=https://raw.githubusercontent.com/kabanero-io/codewind-templates/master/`)

But this doesn't work; Che takes the url and does a GET on `<url>/devfiles/` to get the contents of the `index.json` (and obviously that won't work for GitHub).  If it simply does a GET on `<url>/devfiles/index.json` instead, then I believe it would work.  (it would be a small change here https://github.com/eclipse/che/blob/master/dashboard/src/components/api/devfile-registry.factory.ts#L46)

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by tobespc** [comment]
I'm trying to get that to work by submitting a PR against che to pretty much suggest what you have said

**Comment by l0rd** [comment]
Based on the PR discussion https://github.com/eclipse/che/pull/13645#issuecomment-510093281 I would +1 to set milestone 7.0.0 and merge the PR
@nickboldt @tsmaeder @rhopp @slemeur

**Comment by nickboldt** [comment]
+1, added to che7GA and milestone 7.0.0.

**Comment by makandre** [comment]
Thank you!

**Comment by slemeur** [comment]
@makandre : As the PR been merged, is this issue solved?

**Comment by makandre** [comment]
Hi @slemeur, for my usage I'm packaging a custom assembly where I change the `che.workspace.devfile_registry_url` value to point to my repo with the `index.json`

So I have been using `7.0.0-RC-3.0-SNAPSHOT` as the base che assembly, however it doesn't appear to contain the fix yet.  Am I using the right version?  Is there another version I should be using which contains the fix?  Thanks.

**Comment by slemeur** [comment]
Thanks for your answer @makandre ! 
The fix has been merged yesterday, so you should pull the latest snapshot of RC 3.
How and where are you deploying Che?

**Comment by makandre** [comment]
I just built again with `7.0.0-RC-3.0-SNAPSHOT` but it still does not have the fix

**Comment by makandre** [comment]
Will there be `7.0.0-RC-4.0` images?

**Comment by amisevsk** [comment]
I believe we are currently on `7.0.0-rc-4.0-SNAPSHOT`, rc-3.0 was released a few weeks ago and is not taking current commits (I think @slemeur mistyped)

However, if *all* you are doing to modify the assembly is setting `che.workspace.devfile_registry_url`, this can be done in the current `eclipse/che-server:nightly` image by setting the environment variable 

`CHE_WORKSPACE_DEVFILE__REGISTRY__URL`

in the container. Generally properties can be overriden at runtime via env vars using the translation `'_' -> '__'; '.' -> '_'; toUppercase()`.

**Comment by tobespc** [comment]
we have tested the master branch and can see it in there ok

**Comment by makandre** [comment]
@amisevsk Thanks for the clarification.  I'm able to verify it works now.

**Comment by amisevsk** [comment]
@makandre No problem, happy to help! There's a little more information in an (old, but still valid) doc: https://www.eclipse.org/che/docs/che-6/properties.html#properties-and-environment-variables

**Comment by slemeur** [comment]
Excellent! Thanks @amisevsk for following-up !
