### ISSUE TITLE
Go sample `permission denied` issues with dependencies

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#13823]
### Description
There are issues with current Go devfile sample https://github.com/eclipse/che-devfile-registry/tree/master/devfiles/go. This is the sample project: https://github.com/golang/example. We have tasks just for its `outyet` part, which works ok. However, there are many other Go files with main functions. Problematic ones are those with 3rd party dependencies, like this one https://github.com/golang/example/blob/master/gotypes/skeleton/main.go. When theia tries to build the file, it fails with `permission denied` to `/go` directory, when it try to download dependency there.
![go_permissiondenied](https://user-images.githubusercontent.com/1160903/61108817-a9537200-a483-11e9-8c39-bad1a195b21d.png)

### Reproduction Steps
 - create workspace from devfile https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/go/devfile.yaml
 - open `gotypes/skeleton/main.go`
 - do any changes to file to kick in the compiler and save the file

There is another issue with clone path #13796 which affects also this devfile. This patch has to be applied to the devfile. Without that, project is cloned to `... golang/example/example`. Once the issue is fixed, this patch must not be needed.
```
diff --git a/devfiles/go/devfile.yaml b/devfiles/go/devfile.yaml
index 8c09ff9..508a8c7 100644
--- a/devfiles/go/devfile.yaml
+++ b/devfiles/go/devfile.yaml
@@ -8,7 +8,7 @@ projects:
   source: 
     type: git
     location: https://github.com/golang/example.git
-  clonePath: src/github.com/golang/example/
+  clonePath: src/github.com/golang/
 components:
 -
   type: chePlugin
```

**OS and version:**    
7.0.0-rc-4.0-SNAPSHOT

**Diagnostics:** 
running `go: Current GOPATH` task say `/go:/projects is the current GOPATH.`
I believe this is the issue. `GOPATH` set in the plugin here https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/ms-vscode/go/0.11.0/meta.yaml#L20 have `/go` as first and this is where it tries to download the dependency, but has no permissions there.

**Comment by sparkoo** [comment]
When we fix this one, the realworld sample will probably also work and we could reconsider to include also that one into 7.0.0.

**Comment by rhopp** [comment]
After discussing with @sparkoo I believe this should be dealt with in Che 7 Endgame.
Mainly because of two reasons:
1) Adding ANY external dependency will result in user not being able to develop in this workspace.
2) The repository cloned by default in this go devfile contains multiple examples, of which some of them contains external dependencies.  (if user would try them, he will get these errors)

**Comment by tsmaeder** [comment]
So the issue is that "/go" is first in the gopath in the devfile and go language tools are downloading dependencies there?

**Comment by sparkoo** [comment]
@tsmaeder that's my theory. However, I don't know how to patch and deploy Go plugin locally so I haven't test it in Che.

**Comment by l0rd** [comment]
Can this be worked out by @amisevsk and @ibuziuk in the context of https://github.com/eclipse/che/issues/13454?

**Comment by tsmaeder** [comment]
@l0rd I asked @tolusha to have a look and analyze what a fix should look like. Usually, the folder /go should not be writeable, right? That would require sudo (which we don't want). 
Question is: since we "own" the container, should we make /go writeable or do we need another workaround?

**Comment by l0rd** [comment]
I think we have a few options (in order of preference):

1) Use `${HOME}/go` instead of `/go`
2) Mount folder `/go`
3) `chmod /go` as we do [for /etc/passwd](https://github.com/eclipse/che-devfile-registry/blob/master/arbitrary-users-patch/Dockerfile#L4)

**Comment by amisevsk** [comment]
I don't know that this issue has a convenient solution; Go has issues with developing outside of `${GOPATH}` (e.g. when I'm working on che-plugin-broker, the code is checked out to `${GOPATH}/src/github.com/eclipse/che-plugin-broker`). 

Go 1.11 adds "preliminary" support [1] for modules and 1.12 improves this [2] in preparation for it being a default in 1.13 later this year. This would resolve our issue, but
1. Our current devfile runs on go version `1.10.7`
2. Projects need to convert to the new format (create a `go.mod` file). This can in some cases be done automatically but still needs to be done.

With out current version of Go, the solution would look something like
1. Set `${GOPATH}=/projects`
2. Check out workspace code to a `$GOPATH` compatible directory (e.g. `/projects/src/github.com/eclipse/che-plugin-broker`)
3. Work in this directory.

[1] - [Docs on modules](https://golang.org/cmd/go/#hdr-Modules__module_versions__and_more)
[2] - [Relevant Go 1.12 release notes](https://golang.org/doc/go1.12#modules)

**Comment by tolusha** [comment]
Wrong permissions for `/go/pkg` folder.
Easily can be fixed by patching the corresponding docker file for go plugin [1]
```
/go $ ls -l
total 0
drwxrwxrwx    2 0        root           642 Jul 15 06:55 bin
drwxr-xr-x    3 0        root            25 Jul 15 06:55 pkg
drwxrwxrwx    5 0        root            65 Jul 15 06:55 src
```

[1] https://github.com/eclipse/che-theia/blob/master/dockerfiles/remote-plugin-go-1.10.7/Dockerfile#L45

**Comment by tolusha** [comment]
I've just check the PR [1] and it works fine. 
Here is the devfile [2] which uses go plugin [3] with updated docker image

[1] https://github.com/eclipse/che-theia/pull/348
[2] https://github.com/tolusha/devfiles-registry/blob/master/devfiles/go/devfile.yaml#L15
[3] https://github.com/tolusha/plugins-registry/blob/master/plugins/tolusha/go/0.11.0/meta.yaml#L15

**Comment by tsmaeder** [comment]
@tolusha any particular reason you're not proposing a PR with 2) and 3)?

**Comment by tolusha** [comment]
@tsmaeder I don't understand what you mean.

**Comment by tsmaeder** [comment]
Who is going to fix the devfile and plugin to use the new image?

**Comment by tolusha** [comment]
Nobody, the fix will be in the next build of go sidecar container.

**Comment by tsmaeder** [comment]
@sparkoo So can we consider this one fixed now?

**Comment by tsmaeder** [comment]
[Create automated UI test for install Eclipse Che by using OperatorHub UI](https://github.com/eclipse/che/issues/13878)

Would I delay 7.0.0 for this? No I would not!

**Comment by sparkoo** [comment]
@tsmaeder I wasn't able to verify the fix yet. All che-theia containers I've tried still have the bug. Current default is `eclipse/che-theia/7.0.0-next` https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties#L657, which is still failing for me.

**Comment by sparkoo** [comment]
@tolusha I've just tried with `eclipse/che-theia/7.0.0-next` and the issue is still there. Could you please take a look?

**Comment by tolusha** [comment]
@sparkoo 
I confused you. It is needed to check with the latest image for sidecar container which is `eclipse/che-remote-plugin-go-1.10.7` [1] 

[1] https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/ms-vscode/go/latest/meta.yaml#L15

I've just checked and permissions are set correctly. Could you confirm pls?

**Comment by sparkoo** [comment]
@tolusha ok, how could I test it?

**Comment by tolusha** [comment]
1. Stop `go` workspace
2 `minishift ssh`
3 `docker pull docker.io/eclipse/che-remote-plugin-go-1.10.7:7.0.0-next`
4. Start `go` workspace

**Comment by tolusha** [comment]
I see, now it is problem with `/go/pkg/linux_amd64` directory.

```
/go/pkg $ ls -l
total 0
drwxr-xr-x    3 0        root            24 Jul 22  2019 linux_amd64
```

**Comment by tolusha** [comment]
I've introduced PRs to fix the problem.

**Comment by sparkoo** [comment]
yes, works now. thanks.

**Comment by amisevsk** [comment]
@tolusha Has this fix made it into the plugin-registry/sidecar image? Using https://che-plugin-registry.prod-preview.openshift.io/ I'm not seeing the fix for our golang devfile.

**Comment by tolusha** [comment]
@amisevsk correct.
The fix was for sidecar image.
