### ISSUE TITLE
"API rate limit exceeded" because GITHUB_TOKEN was incorrectly applied to che-theia build.sh

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#14529]
There is build error occurred on PR check build 
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/115/console
```
Step 8/32 : ADD https://${GITHUB_TOKEN}:x-oauth-basic@api.github.com/repos/${THEIA_GITHUB_REPO}/git/refs/heads/master /tmp/branch_info.json
ADD failed: failed to GET https://****:x-oauth-basic@api.github.com/repos/theia-ide/theia/git/refs/heads/master with status 403 Forbidden: {"message":"API rate limit exceeded for 66.187.233.202. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}
```
It could be related to this PR https://github.com/eclipse/che-theia/pull/434

Actually, that is the problem of `ADD https://${GITHUB_TOKEN}:x-oauth-basic@api.github.com/repos/che-theia/git/refs/heads/master` command itself: 
there is redirection from **https://${GITHUB_TOKEN}:x-oauth-basic@api.github.com/repos/che-theia/git/refs/heads/master** to https://api.github.com/repositories/83050680/git/refs/heads/master, and second location is without `${GITHUB_TOKEN}:x-oauth-basic@`:
<details>
 <summary>curl log</summary>
 <pre>
Step 9/34 : RUN curl -v -L https://${GITHUB_TOKEN}:x-oauth-basic@api.github.com/repos/${THEIA_GITHUB_REPO}/git/refs/heads/master
 ---> Running in d023f6f1ad15
* Expire in 0 ms for 6 (transfer 0x5628614297a0)
* Expire in 1 ms for 1 (transfer 0x5628614297a0)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Expire in 0 ms for 1 (transfer 0x5628614297a0)

  0     0    0     0    0     0      0      0 
*   Trying 140.82.113.5...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x5628614297a0)
* Connected to api.github.com (140.82.113.5) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [25 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [2856 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [264 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [36 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [36 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=GitHub, Inc.; CN=*.github.com
*  start date: Jul  8 00:00:00 2019 GMT
*  expire date: Jul 16 12:00:00 2020 GMT
*  subjectAltName: host "api.github.com" matched cert's "*.github.com"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 High Assurance Server CA
*  SSL certificate verify ok.
* Server auth using Basic with user '****'
} [5 bytes data]
> GET /repos/theia-ide/theia/git/refs/heads/master HTTP/1.1
> Host: api.github.com
> Authorization: Basic MmRkY2Y5MzMwMTg1MDQ2M2FhYTM1MmM1MDkxOTI5M2NhZjY3OGI5Mzp4LW9hdXRoLWJhc2lj
> User-Agent: curl/7.64.0
> Accept: */*
> 
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [57 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [57 bytes data]
* old SSL session ID is stale, removing
{ [5 bytes data]
< HTTP/1.1 301 Moved Permanently
< Date: Fri, 13 Sep 2019 08:01:57 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 190
< Server: GitHub.com
< Status: 301 Moved Permanently
< X-RateLimit-Limit: 5000
< X-RateLimit-Remaining: 4988
< X-RateLimit-Reset: 1568365262
< X-OAuth-Scopes: admin:repo_hook, public_repo, repo:status, repo_deployment
< X-Accepted-OAuth-Scopes: admin:repo_hook, delete_repo, read:repo_hook, repo, repo:status, repo_deployment, write:repo_hook
< Location: https://api.github.com/repositories/83050680/git/refs/heads/master
< X-GitHub-Media-Type: github.v3; format=json
< Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type
< Access-Control-Allow-Origin: *
< Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
< X-Frame-Options: deny
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
< Content-Security-Policy: default-src 'none'
< Vary: Accept-Encoding
< X-GitHub-Request-Id: A294:044A:159074:249711:5D7B4CF5
< 
* Ignoring the response-body
{ [159 bytes data]

100   190  100   190    0     0   1104      0 --:--:-- --:--:-- --:--:--  1098
* Connection #0 to host api.github.com left intact
* Issue another request to this URL: 'https://api.github.com/repositories/83050680/git/refs/heads/master'
* Found bundle for host api.github.com: 0x56286142d920 [can pipeline]
* Could pipeline, but not asked to!
* Re-using existing connection! (#0) with host api.github.com
* Connected to api.github.com (140.82.113.5) port 443 (#0)
* Expire in 0 ms for 6 (transfer 0x5628614297a0)
} [5 bytes data]
> GET /repositories/83050680/git/refs/heads/master HTTP/1.1
> Host: api.github.com
> User-Agent: curl/7.64.0
> Accept: */*
> 
{ [5 bytes data]
< HTTP/1.1 403 Forbidden
< Date: Fri, 13 Sep 2019 08:01:57 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 258
< Server: GitHub.com
< Status: 403 Forbidden
< X-RateLimit-Limit: 60
< X-RateLimit-Remaining: 0
< X-RateLimit-Reset: 1568363281
< X-GitHub-Media-Type: github.v3; format=json
< Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type
< Access-Control-Allow-Origin: *
< Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
< X-Frame-Options: deny
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
< Content-Security-Policy: default-src 'none'
< X-GitHub-Request-Id: A294:044A:15907A:249717:5D7B4CF5
< 
{ [258 bytes data]

100{
  "message": "API rate limit exceeded for 66.187.233.202. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
   258  100   258    0     0   1270      0 --:--:-- --:--:-- --:--:--  1270
* Connection #0 to host api.github.com left intact
 </pre>
</details>

### Che-theia version
from master branch

### Steps to reproduce
export GITHUB_TOKEN=....
./build.sh --pr --skip-tests

### Environment
CRW Central CI

**Comment by mmorhun** [comment]
Unset of GITHUB_TOKEN is fixed in https://github.com/eclipse/che-theia/pull/436, but we have another problem which might fail the build.

**Comment by dmytro-ndp** [comment]
@mmorhun: you are right. There is another problem remained with `ADD https://${GITHUB_TOKEN}:x-oauth-basic@api.github.com/repos/che-theia/git/refs/heads/master` command itself.
I have updated description.
