### ISSUE TITLE
Ephemeral toggle is confusing

### ISSUE THREAD

**Issue by maxandersen** [eclipse-che/che#15721]
Normal users don't know what Ephemeral mode means (nor should they)  and the help text is not helping.

![2020-01-16_11-50-11](https://user-images.githubusercontent.com/54129/72518866-805ad200-3856-11ea-89d5-c28258cd932b.png)

What is a PVC ? 

Suggestion:
Call it something like Temporary Storage or Persistent Disk Volume or something that at least gives a normal human a chance to guess what that toggle is about.

**Comment by sleshchenko** [comment]
Proposed toggle title: `Temporary Storage`,
Message for pop-up: `Temporary Storage allows containers to share volumes but they are not persisted (all the data will be lost after workspace restart)`

If someone has any suggestions/remarks - p.lease comment here

**Comment by ibuziuk** [comment]
@maxandersen WDYT ^ ?

**Comment by maxandersen** [comment]
Muuch better :) 

btw. another thing that i'm not sure if this tooltip is the right place for - it seems with temporary storage you also end up with *less* space than with a persistent one...like a basic gradle build like jbang can't run on temporary storage but it can when not chosen.

**Comment by ibuziuk** [comment]
> it seems with temporary storage you also end up with less space than with a persistent one.

yeah, good point but storage size for ephemeral is a separate issue that requires a more investigation. I believe for the next release we can start with just improving the naming / tooltip

**Comment by maxandersen** [comment]
Agreed @ibuziuk just not sure where to report this "quirk" that I assume is very deployment specific. if you can let me know I'll open issue for it.

**Comment by ibuziuk** [comment]
@maxandersen this one is cluster / config specific, so please open it against https://github.com/redhat-developer/rh-che/issues

**Comment by beaumorley** [comment]
Can we say something in the tool tip about why they would keep it turned on?  If we just say their data will be lost, will users turn it off? What about something with a positive spin like this (guessing here as to why they may want to keep it on):

Temporary Storage  [toggle control here]
Tooltip: Temporary Storage allows for faster I/O but is not persistent. All data will be lost after the workspace restarts.

**Comment by beaumorley** [comment]
What about?

Temporary Storage allows for faster I/O but has limited storage and is not persistent.

**Comment by maxandersen** [comment]
I think the limited storage is very much dependent on the underlying cluster configuration so it would not be true in all installations.

That’s at least how I understand the current situation.

**Comment by beaumorley** [comment]
Hmm. Is this too complicated for a tooltip? Is it accurate?

*****
Temporary Storage allows for faster I/O. It may have limited storage for certain configurations and is not persistent.

*****

I feel like the original second sentence (All data will be lost after the workspace restarts.) is redundant. So I suggest removing that and expanding on Max's pain point.

**Comment by beaumorley** [comment]
Here are some mockups of how the updated ephemeral toggle might look. For the existing UI, change the label and the tooltip copy.  This will need to be done on the New Workspace screen and the Workspace > Overview screen. Like this:

![image](https://user-images.githubusercontent.com/52013984/73020429-97b83300-3df3-11ea-9f24-ca0ea06d3bc8.png)

![image](https://user-images.githubusercontent.com/52013984/73020444-a0a90480-3df3-11ea-87e6-cedaf3d7378e.png)

For the new getting started page, I recommend do something like this:

![image](https://user-images.githubusercontent.com/52013984/73021090-db5f6c80-3df4-11ea-9345-c8213bbec134.png)

- Move search control to the left
- Put the toggle next to the number of items

**Comment by sleshchenko** [comment]
New wording on Create Workspace and Workspace Details are already addressed in https://github.com/eclipse/che/pull/15818

There is a separate issue to introduce Temporary Storage on Get Started page https://github.com/eclipse/che/issues/15855

**Comment by SDAdham** [comment]
Can we have a clarification on what is the use case for it? When do we need to toggle it on? It still doesn't really clarify.
