### ISSUE TITLE
Redesign SelfSigned cert error page

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#16065]
### Is your task related to a problem? Please describe.
The current self-signed cert error page is aggressive and frightening a bit
![Screenshot from 2020-02-12 09-34-18](https://user-images.githubusercontent.com/6310786/74324790-3ea74380-4d90-11ea-8d71-28aed7ca20e3.png)

### Describe the solution you'd like
It would be cool to redesign this page in Che style.

### Additional context
Florent: Woot! I’m finding that error message is looking more to a Browser error (scary one) than Eclipse Che (warning) (logo, etc) message but maybe it’s the goal ?
	Stevan: +1 for having a more “Che” warning - but don’t forget to allow branding it

**Comment by sleshchenko** [comment]
@beaumorley Could you give your suggestion to design?

**Comment by beaumorley** [comment]
@sleshchenko When/where exactly does this show up? If this is not something that needs to be a real warning, we want to remove the red.  I can give a design suggestion if you LMK the path to get to it. 

For example:
We are using an alert design when a workspace is started and also when an IDE is opened and there is an error message. In both scenarios, we put the message in an alert that kind of like this.  
https://www.patternfly.org/v4/documentation/react/components/alert

LMK where I would see this error and I can give you more direction!

**Comment by sleshchenko** [comment]
@beaumorley It's an error page user gets because it's not possible to open dashboard because it's not possible to authorize a user.
So, it's not possible to show anything for the user until it does not solve the issue (import CA into a browser or add an exclusion for needed (keycloak) host).

**Comment by beaumorley** [comment]
I did not realize it was not possible for the user to move forward. Thanks for the demo @sleshchenko. Here are two ideas.

1.) Black background. 
![image](https://user-images.githubusercontent.com/52013984/74865475-26e73680-531f-11ea-874a-cb2e0735ab9a.png)

2.) White background (I used some of the loading screen design here).
![image](https://user-images.githubusercontent.com/52013984/74865550-48482280-531f-11ea-81f6-5988a7453f5b.png)

**Comment by sleshchenko** [comment]
I also propose to remove the second solution since it's not really working. Once user adds exclusions for Che and Keycloak host - he will face the same issue with Plugin Registry, Devfile Registry, each workspace server hosts. So, it makes more sense to improve UX to go through first working solution instead of proposing simpler but not fully working )

**Comment by olexii4** [comment]
done

**Comment by strongit** [comment]
https://github.com/eclipse/che/issues/17391#issuecomment-659116683
 che:7.15.2 Still have the issues?
