### ISSUE TITLE
che-theia-all.devfile.yaml fails when running build ... DEV che-theia

### ISSUE THREAD

**Issue by tomgeorge** [eclipse-che/che#16413]
### Describe the bug

1. Create a new workspace
2. import devfile https://raw.githubusercontent.com/eclipse/che-theia/master/devfiles/che-theia-all.devfile.yaml
3. When the workspace starts, run init ... DEV che-theia
4. run build ... DEV che-theia

The build step will fail at the `yarn` step in build.

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: 7.9.1 che.openshift.io

### Steps to reproduce

1. Create a new workspace
2. import devfile https://raw.githubusercontent.com/eclipse/che-theia/master/devfiles/che-theia-all.devfile.yaml
3. When the workspace starts, run init ... DEV che-theia
4. run build ... DEV che-theia

### Expected behavior

che-theia should build

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [x] other: Hosted Che

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by ibuziuk** [comment]
@vitaliy-guliy I know https://github.com/eclipse/che-theia/pull/627 is merged now. Could you please take a look at this issue (I suspect that this could have been already addressed)

**Comment by vitaliy-guliy** [comment]
@ibuziuk yes, I will take a look and fix the build command if it's necessary.

**Comment by tomgeorge** [comment]
Is there any update on this? It is still not building for me with https://raw.githubusercontent.com/eclipse/che-theia/master/devfiles/che-theia-all.devfile.yaml

```
@eclipse-che/theia-logging: error Command failed with exit code 2.
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: yarn run lint
lerna ERR! 
lerna ERR! Oops! Something went wrong! :(
lerna ERR! 
lerna ERR! ESLint: 6.8.0.
lerna ERR! 
lerna ERR! ESLint couldn't find the plugin "@typescript-eslint/eslint-plugin".
lerna ERR! 
lerna ERR! (The package "@typescript-eslint/eslint-plugin" was not found when loaded as a Node module from the directory "/projects/che-theia/extensions/eclipse-che-theia-logging".)
lerna ERR! 
lerna ERR! It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:
lerna ERR! 
lerna ERR!     npm install @typescript-eslint/eslint-plugin@latest --save-dev
lerna ERR! 
lerna ERR! The plugin "@typescript-eslint/eslint-plugin" was referenced from the config file in "../../.eslintrc.js » ./configs/eslint.json » ./eslint.che-theia.json".
lerna ERR! 
lerna ERR! If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.
lerna ERR! 
lerna ERR! error Command failed with exit code 2.
lerna ERR! 
lerna ERR! $ eslint --cache=true --no-error-on-unmatched-pattern=true "{src,test}/**/*.{ts,tsx}"
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! 
lerna ERR!     at Promise.all.then.arr (/projects/theia/node_modules/execa/index.js:236:11)
lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.
{ Error: Command failed: yarn run lint

Oops! Something went wrong! :(

ESLint: 6.8.0.

ESLint couldn't find the plugin "@typescript-eslint/eslint-plugin".

(The package "@typescript-eslint/eslint-plugin" was not found when loaded as a Node module from the directory "/projects/che-theia/extensions/eclipse-che-theia-logging".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install @typescript-eslint/eslint-plugin@latest --save-dev

The plugin "@typescript-eslint/eslint-plugin" was referenced from the config file in "../../.eslintrc.js » ./configs/eslint.json » ./eslint.che-theia.json".

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.

error Command failed with exit code 2.

$ eslint --cache=true --no-error-on-unmatched-pattern=true "{src,test}/**/*.{ts,tsx}"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

    at Promise.all.then.arr (/projects/theia/node_modules/execa/index.js:236:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 2,
  killed: false,
  stdout:
   '$ eslint --cache=true --no-error-on-unmatched-pattern=true "{src,test}/**/*.{ts,tsx}"\ninfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\n',
  stderr:
   '\nOops! Something went wrong! :(\n\nESLint: 6.8.0.\n\nESLint couldn\'t find the plugin "@typescript-eslint/eslint-plugin".\n\n(The package "@typescript-eslint/eslint-plugin" was not found when loaded as a Node module from the directory "/projects/che-theia/extensions/eclipse-che-theia-logging".)\n\nIt\'s likely that the plugin isn\'t installed correctly. Try reinstalling by running the following:\n\n    npm install @typescript-eslint/eslint-plugin@latest --save-dev\n\nThe plugin "@typescript-eslint/eslint-plugin" was referenced from the config file in "../../.eslintrc.js » ./configs/eslint.json » ./eslint.che-theia.json".\n\nIf you still can\'t figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.\n\nerror Command failed with exit code 2.\n',
  failed: true,
  signal: null,
  cmd: 'yarn run lint',
  timedOut: false,
  exitCode: 1 }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by vitaliy-guliy** [comment]
@tomgeorge I see two issues here:

1. Sometimes theia does not want to be build when `che-thea` is not in `/projects/theia/che` directory. In our case `che-theia` is cloned to `/projects/che-theia`. When running `init ... DEV che-theia` command, the new alias for https://github.com/eclipse/che-theia repository will be created, which will point in on local `/projects/che-theia` directory.
But it somehow works when building Che-Theia docker image https://github.com/eclipse/che-theia/blob/master/dockerfiles/theia/Dockerfile#L53
It's necessary to investigate it in more detail.

But you can try to init `che-theia` by hands. For that you need to open a terminal in `che-dev` container and run 

$ cd /projects/theia
$ che-theia init
$ yarn

It will clone `che-theia` to `/projects/theia/che/che-theia` and build.

2. After initializing Che-Theia by hands, I was not able to build having another error
```
lerna ERR! [compile] src/browser/che-task-main.ts(37,55): error TS2345: Argument of type '(event: TaskInfo) => Promise<void>' is not assignable to parameter of type '(e: TaskInfo) => any'.
lerna ERR! [compile]   Types of parameters 'event' and 'e' are incompatible.
lerna ERR! [compile]     Type 'import("/projects/theia/packages/task/lib/common/task-protocol").TaskInfo' is not assignable to type 'import("/projects/theia/che/che-theia/extensions/eclipse-che-theia-plugin/src/che").TaskInfo'.
lerna ERR! [compile]       The types of 'config._scope' are incompatible between these types.
lerna ERR! [compile]         Type 'TaskConfigurationScope' is not assignable to type 'string | undefined'.
lerna ERR! [compile]           Type 'TaskScope.Workspace' is not assignable to type 'string | undefined'.
lerna ERR! [compile] src/browser/che-task-main.ts(38,52): error TS2345: Argument of type '(event: TaskExitedEvent) => Promise<void>' is not assignable to parameter of type '(e: TaskExitedEvent) => any'.
lerna ERR! [compile]   Types of parameters 'event' and 'e' are incompatible.
lerna ERR! [compile]     Type 'import("/projects/theia/packages/task/lib/common/task-protocol").TaskExitedEvent' is not assignable to type 'import("/projects/theia/che/che-theia/extensions/eclipse-che-theia-plugin/src/che").TaskExitedEvent'.
lerna ERR! [compile]       Types of property 'config' are incompatible.
lerna ERR! [compile]         Type 'import("/projects/theia/packages/task/lib/common/task-protocol").TaskConfiguration | undefined' is not assignable to type 'import("/projects/theia/che/che-theia/extensions/eclipse-che-theia-plugin/src/che").TaskConfiguration | undefined'.
lerna ERR! [compile]           Type 'import("/projects/theia/packages/task/lib/common/task-protocol").TaskConfiguration' is not assignable to type 'import("/projects/theia/che/che-theia/extensions/eclipse-che-theia-plugin/src/che").TaskConfiguration'.
lerna ERR! [compile] src/browser/task-config-service.ts(52,13): error TS2322: Type '{ taskId: number; widgetOptions: { area: "bottom"; }; mode: WidgetOpenMode; taskInfo: TaskInfo | undefined; }' is not assignable to type 'TaskTerminalWidgetOpenerOptions'.
lerna ERR! [compile]   Object literal may only specify known properties, and 'taskId' does not exist in type 'TaskTerminalWidgetOpenerOptions'.
lerna ERR! [compile] src/node/che-task-service.ts(42,55): error TS2345: Argument of type 'import("/projects/theia/packages/task/lib/common/task-protocol").TaskConfiguration' is not assignable to parameter of type 'import("/projects/theia/che/che-theia/extensions/eclipse-che-theia-plugin/src/che").TaskConfiguration'.
lerna ERR! [compile] src/node/che-task-service.ts(43,94): error TS2322: Type 'import("/projects/theia/che/che-theia/extensions/eclipse-che-theia-plugin/src/che").TaskInfo' is not assignable to type 'import("/projects/theia/packages/task/lib/common/task-protocol").TaskInfo'.
lerna ERR! [compile]   The types of 'config._scope' are incompatible between these types.
lerna ERR! [compile]     Type 'string | undefined' is not assignable to type 'TaskConfigurationScope'.
lerna ERR! [compile]       Type 'undefined' is not assignable to type 'TaskConfigurationScope'.
lerna ERR! [compile] src/node/che-task-service.ts(47,17): error TS2322: Type 'CheTask' is not assignable to type 'Task'.
lerna ERR! [compile]   Types of property 'fireTaskExited' are incompatible.
lerna ERR! [compile]     Type '(event: import("/projects/theia/che/che-theia/extensions/eclipse-che-theia-plugin/src/che").TaskExitedEvent) => void' is not assignable to type '(event: import("/projects/theia/packages/task/lib/common/task-protocol").TaskExitedEvent) => void'.
lerna ERR! [compile] src/node/che-task-service.ts(115,56): error TS2345: Argument of type 'import("/projects/theia/packages/task/lib/common/task-protocol").TaskInfo' is not assignable to parameter of type 'import("/projects/theia/che/che-theia/extensions/eclipse-che-theia-plugin/src/che").TaskInfo'.
lerna ERR! [compile] src/node/che-task-service.ts(118,5): error TS2416: Property 'fireTaskExited' in type 'CheTask' is not assignable to the same property in base type 'Task'.
lerna ERR! [compile]   Type '(event: import("/projects/theia/che/che-theia/extensions/eclipse-che-theia-plugin/src/che").TaskExitedEvent) => void' is not assignable to type '(event: import("/projects/theia/packages/task/lib/common/task-protocol").TaskExitedEvent) => void'.
lerna ERR! [compile]     Types of parameters 'event' and 'event' are incompatible.
lerna ERR! [compile]       Type 'import("/projects/theia/packages/task/lib/common/task-protocol").TaskExitedEvent' is not assignable to type 'import("/projects/theia/che/che-theia/extensions/eclipse-che-theia-plugin/src/che").TaskExitedEvent'.
lerna ERR! [compile] error Command failed with exit code 2.
lerna ERR! [compile] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! [compile] yarn compile exited with code 2
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! 
lerna ERR!     at Promise.all.then.arr (/projects/theia/node_modules/execa/index.js:236:11)
{ Error: Command failed: yarn run build
error Command failed with exit code 1.
```

**Comment by tomgeorge** [comment]
@vitaliy-guliy I have seen the same error when trying `che-theia init` and `yarn` in a terminal as well.

**Comment by tomgeorge** [comment]
Hi, just checking in to see if there is any update on this?

**Comment by vitaliy-guliy** [comment]
@tomgeorge  You should be able to init Che-Theia with `che-theia init` and build with `yarn`.
The devfile is still unchanged, I will try to update it soon.

**Comment by azatsarynnyy** [comment]
In some cases, yarn build fails after applying `che-theia init` with `--alias` parameter
https://github.com/eclipse/che-theia/blob/4d2f05a57d9263b741d844000718a3100e8d9497/devfiles/che-theia-all.devfile.yaml#L55

The workaround is to call `che-theia init` command in `/projects/theia` folder.

**Comment by azatsarynnyy** [comment]
setting P1 as it's related to dogfooding

**Comment by azatsarynnyy** [comment]
I've removed `--alias` for `che-theia init` in [`che-theia-all.devfile.yaml`](https://raw.githubusercontent.com/eclipse/che-theia/master/devfiles/che-theia-all.devfile.yaml)
Looks like yarn doesn't work correctly with the sources placed in the folders of the same level.
