### ISSUE TITLE
Che build in the root directory fails on a clean check-out

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-che/che#1858]
Followed https://eclipse-che.readme.io/docs/create-and-build-extensions
Building Che fails with the error below

**Reproduction Steps:**
1. check-out the code (used Yatta Profile)
2. install all prerequisites
3. executed mvn clean install in the root source directory

assembly build is successful afterwards

**Che version:**    master and 4.4 tag
**OS and version:** Linux Ubuntu

**Additional information:**

Tests run: 81, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 9.044 sec <<< FAILURE! - in TestSuite
testKill(org.eclipse.che.api.core.util.ProcessUtilTest)  Time elapsed: 1.061 sec  <<< FAILURE!
java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.che.api.core.util.ProcessUtil
    at org.eclipse.che.api.core.util.ProcessUtilTest.testKill(ProcessUtilTest.java:67)

Results :

Failed tests: 
  ProcessUtilTest.testKill:67 NoClassDefFound Could not initialize class org.ecl...

Tests run: 81, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Che Parent ......................................... SUCCESS [  5.222 s]
[INFO] Che Core Parent .................................... SUCCESS [  0.120 s]
[INFO] Che Core :: Commons :: Parent ...................... SUCCESS [  0.907 s]
[INFO] Che Core :: Commons :: Annotations ................. SUCCESS [  6.090 s]
[INFO] Che Core :: Commons :: Java API extension classes .. SUCCESS [ 10.703 s]
[INFO] Che Core :: Commons :: Dependency Injecting ........ SUCCESS [  9.119 s]
[INFO] Che Core :: Commons :: Json helpers ................ SUCCESS [  5.646 s]
[INFO] Che Core :: Commons :: XML ......................... SUCCESS [ 11.582 s]
[INFO] Che Core :: Commons :: Scheduler service ........... SUCCESS [  8.789 s]
[INFO] Che Core :: Commons :: Utilities for tests ......... SUCCESS [  3.649 s]
[INFO] Che Core :: API :: DTO ............................. SUCCESS [ 17.104 s]
[INFO] Che Core :: API :: DTO Maven Plugin ................ SUCCESS [  9.207 s]
[INFO] Che Core :: API :: Core ............................ FAILURE [ 16.424 s]
[INFO] Che Core :: API :: Model ........................... SKIPPED
[INFO] Che Master Parent .................................. SKIPPED
[INFO] Che Core :: API :: Authentication .................. SKIPPED
[INFO] Che Core :: API :: Machine :: Shared ............... SKIPPED

**Comment by TylerJewell** [comment]
This seems to be linked to #1861.

**Comment by JamesDrummond** [comment]
@eivantsov Was this ever resolved. If not can you provide a status label.

**Comment by ghost** [comment]
@JamesDrummond it should be tested with the updated Yatta profile.

**Comment by JonasHelming** [comment]
I just tested on master, 4.6.1 and 4.6.0
None of those build succesfully (mvn clean install in the root directory)

If you do a fresh checkout using the Yatta Profile, the build triggered in the IDE runs successfully. That lets me assume that the Yatta installer executes some custom mvn command, which probably ignores something?

**Comment by JonasHelming** [comment]
I guess the Yatta Installer executes mvn clean install in the /assembly directory

**Comment by ghost** [comment]
@JonasHelming yes, I confirm the build is a success.

**Comment by ghost** [comment]
@JonasHelming should I close the issue now when Yatta profile has been updated?

**Comment by JonasHelming** [comment]
If you just clone the Che repository and execute mvn clean install in the root directory (not the assembly folder), does this build work for you?

**Comment by zenobios** [comment]
@JonasHelming The Yatta profile executes the following maven launch configurations:
1. BuildCheCore: `mvn clean install -Dfindbugs.skip=true -Dskip-validate-sources=true -DskipTests=true -Dmdep.analyze.skip=true`. Base directory: che\core
2. BuildChePlugins: `mvn clean install -Dfindbugs.skip=true -Dskip-validate-sources=true -DskipTests=true -Dmdep.analyze.skip=true`. Base directory: che\plugins
3. BuildCheWSAgent: `mvn clean install -Dfindbugs.skip=true -Dskip-validate-sources=true -DskipTests=true -Dmdep.analyze.skip=true`. Base directory: che\wsagent
4. BuildCheIDE: `mvn clean install -Dfindbugs.skip=true -Dskip-validate-sources=true -DskipTests=true -Dmdep.analyze.skip=true`. Base directory: che\ide
5. BuildCheWSMaster: `mvn clean install -Dfindbugs.skip=true -Dskip-validate-sources=true -DskipTests=true -Dmdep.analyze.skip=true`. Base directory: che\wsmaster

The steps are required to generate required code within the different projects.

**Comment by JonasHelming** [comment]
Actually, this issue is not really about the Yatta Profile.
The main build is failing after a clean check-out for me...

**Comment by ghost** [comment]
@JonasHelming can you share the entire stacktrace?

**Comment by JonasHelming** [comment]
There is no stacktrace, but i can share the log :-)
The following is the result of:

git clone https://github.com/eclipse/che.git
cd che
mvn clean install

Please note that the build fails at different stages on master, 4.6.0 and 4.6.1

[log.txt](https://github.com/eclipse/che/files/408503/log.txt)

**Comment by ghost** [comment]
@JonasHelming can you export M2_HOME env in your system? This should fix it.

**Comment by JonasHelming** [comment]
After setting M2_Home is gets further, but still fails...
I added the M2_HOME hint to https://github.com/eclipse/che/wiki/Development-Workflow
[log2.txt](https://github.com/eclipse/che/files/413171/log2.txt)

**Comment by TylerJewell** [comment]
@JonasHelming @ddementieva - any update here?

**Comment by ghost** [comment]
@TylerJewell I cannot reproduce this one on my Ubuntu.

@JonasHelming where does it fail now? Can you share your build command output?

**Comment by pavandaga** [comment]
The issue is replicable on Windows. The superdevmode does not work in Windows.

**Comment by TylerJewell** [comment]
I am going to close this - because it will not be possible for a clean checkout to do `mvn clean install` without some additional things being added.  We have updated the docs to make it clear what must be installed for different modules to pass.  You should be able to skip tests and get a clean build after a checkout as well.
