### ISSUE TITLE
[Error] when configuring Superdev Mode for Eclipse

### ISSUE THREAD

**Issue by BingxuHong** [eclipse-che/che#1861]
**I tried to configure Superdev Mode for Eclipse, but there was an error while Compiling module org.eclipse.che.ide.IDE.**

![image](https://cloud.githubusercontent.com/assets/20534093/16948432/977c0bc0-4def-11e6-84e5-6fcb220c5ded.png)

**The following is my dev env and what I did:** 
## Dev env:

**Che version:**    [latest]  
**OS and version:** [windows 10]  
**Docker version:** [docker toolbox]  
**Che install:**    [Yatta]   
## What I did:
1. Install pre-requirements and download source from Yatta.
2. mvn clean install at \che\assembly.
3. Configure Superdev Mode following the website.
   https://eclipse-che.readme.io/docs/setup-che-workspace
   And my Arguments is: 
   -noincremental 
   -src target/generated-sources/gen
   org.eclipse.che.ide.IDE

I didn't make any change to the source code, and all my settings are following the Eclipse Che Documents in the web site.

**Comment by TylerJewell** [comment]
@BingxuHong - we will have QA take a look at the instructions and the docs.  Question - you said you used the Yatta installer.  Did you get the source code through the Yatta installer, too?  Trying to understand which pieces came from the repo vs. Yatta.  Thanks.

**Comment by ghost** [comment]
@TylerJewell looks like there are issues with Yatta installer. Not all modules are imported. I am investigating it an the moment.

**Comment by BingxuHong** [comment]
@TylerJewell All of the source code were automatically downloaded through the Yatta installer. And I didn't make any change about source code.

**Comment by TylerJewell** [comment]
Ok, seems like this is related to #1858 and that there is an issue with the yatta installer.  Maybe you can try just cloning the repository without the yatta installer and trying it from scratch?

**Comment by BingxuHong** [comment]
@TylerJewell Actually I want to try to debug Eclispse Che source code. But I'm not familiar with the Java language and the Eclispse IDE. I have no idea to make it without any guide. Anyway, thanks for your answer. I will try outer ways..

**Comment by TylerJewell** [comment]
We have these pages on the docs which document how to setup a development environment for Che for building extensions.  It's how we debug the core code.  We haven't added these links into the wiki yet, but will do so.

https://eclipse-che.readme.io/docs/setup-che-workspace

**Comment by BingxuHong** [comment]
@TylerJewell The web site you linked is that I was following to configure Superdev mode today.. Is there a way to debug the core code except for Google Plug-in?

**Comment by TylerJewell** [comment]
I am not sure I understand the question.  Che is comprised of three systems:
1. Che server
2. Workspace plugins, which are server-side in a workspace.
3. IDE plugins, which are compiled into JavaScript.

Items 1 and 2, do not need GWT for debugging. They are Java apps that run in a Tomcat server, so you can just debug them using any Java IDE debugger connectivity.  Tomcat has its debug port published, so you can connect to that.

The GWT superdev mode is for debugging the IDE extensions only.

I think we document all of this properly on the pages that you have.  Is there something missing?

**Comment by BingxuHong** [comment]
@TylerJewell Thank you. As you said, I will get the source code from the repository and try it again.

**Comment by ghost** [comment]
@BingxuHong it looks like when Yatta profile imports a project not all modules are imported, and the error is caused by missing modules. There are related issues:

https://github.com/eclipse/che/issues/1858
https://github.com/eclipse/che/issues/1740

**Comment by zenobios** [comment]
@BingxuHong We just fixed the issue #1740. Now all all required modules are imported into the workspace.

**Comment by BingxuHong** [comment]
@zenobios  I deleted my workspace and downloaded the source code from Yatta Installer again. The error seems to be clear at the Project Explorer, but when I try to run Super dev mode, there was still that error massage.

![image](https://cloud.githubusercontent.com/assets/20534093/16985208/fc355b50-4eb9-11e6-80bd-5d7ba48f5d4d.png)

By the way, It looks like there is a problem with Projects structure in the new Yatta profile. It loaded the same project twice.
![image](https://cloud.githubusercontent.com/assets/20534093/16985341/b1de03c6-4eba-11e6-87cd-902d4ad4ff11.png)

**Comment by zenobios** [comment]
If it's a problem with having both parent and child maven projects in the workspace, try to close/delete (make sure to only delete it from the workspace)  the parent project and see if it works. 

I'm currently not in the office so I can't try it myself right now.

**Comment by BingxuHong** [comment]
Can any one teach me how to set up eclipse to debug like the video from the link below?
I want to connect eclipse to the tomcat already running for debug.
https://www.youtube.com/watch?v=MSiIGBmGBEw&app=desktop

**Comment by BingxuHong** [comment]
I dealt with the issue #1876 , even though I don't know how it works this time, because I followed same steps as last time.
1. Install pre-requirements and download source from Yatta.
2. mvn clean install at \che\assembly.
3. run '**che --debug start**' at \che\assembly\assembly-main\target\eclipse-che-4.6.0-SNAPSHOT\eclipse-che-4.6.0-SNAPSHOT\bin.
4. debug remote Java Application in Eclispse IDE. 
   ![image](https://cloud.githubusercontent.com/assets/20534093/17020765/60d73ffa-4f7e-11e6-91d4-0e06dd9e29d1.png)

Then debugger stopped at the breakpoint.
![image](https://cloud.githubusercontent.com/assets/20534093/17021079/614c390c-4f80-11e6-97f0-ffd978d9dcb5.png)
![image](https://cloud.githubusercontent.com/assets/20534093/17021093/7427c9ba-4f80-11e6-9c1a-745bbe75ebbe.png)

Now, I will try the Super dev mode..
Anyway, Thank you.

**Comment by JamesDrummond** [comment]
@BingxuHong Have all your issues been resolved on this?

**Comment by BingxuHong** [comment]
@JamesDrummond Not yet. I couldn't make Superdev mode to work.. Recently, I had been working on different projects so I am not sure.

**Comment by ghost** [comment]
@BingxuHong https://github.com/eclipse/che/issues/1740 it should work now. Are you seeing the same super dev mode error?

**Comment by BingxuHong** [comment]
@eivantsov @JamesDrummond I updated the Yatta Profile then tried it again. But it is still not working. 

![image](https://cloud.githubusercontent.com/assets/20534093/17472335/329992fe-5d85-11e6-92d4-45b3ad3344cd.png)

**Comment by ghost** [comment]
@BingxuHong can you share your superdev mode config? As a screenshot.

**Comment by BingxuHong** [comment]
@eivantsov 

![image](https://cloud.githubusercontent.com/assets/20534093/17472669/632fa028-5d87-11e6-80ea-1690151e8f07.png)

![image](https://cloud.githubusercontent.com/assets/20534093/17472674/69db90e4-5d87-11e6-95be-d8b1fa7482aa.png)

![image](https://cloud.githubusercontent.com/assets/20534093/17472684/764514a4-5d87-11e6-83d5-d7b8c8c2cc8c.png)

**Comment by TylerJewell** [comment]
@eivantsov @ddementieva - do we have an update?

**Comment by ghost** [comment]
@TylerJewell not yet. Will do this week

**Comment by ghost** [comment]
@BingxuHong we tried it with the same run configurations on 2 different Ubuntu machines. @ddementieva can confirm it works on her machine as well.

We haven't tried it on Windows though. I think that your problem is related with some missing sources - thus invalid import.

**Comment by pavandaga** [comment]
The superdevmode does not work on Eclipse in Windows

**Comment by slemeur** [comment]
Closing due to inactivity on this issue. 
Please refer to the developer guide: https://github.com/eclipse/che/wiki/Development-Workflow for more info
