### ISSUE TITLE
[minikube] Cannot start workspace if the plugin has CPU limitation

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#18633]
### Describe the bug

It's impossible to start a workspace on `minikube` if the devfile refers on a plugin that describes a sidecar container with some CPU limitation. The problem was noticed while working on https://github.com/eclipse/che/issues/16685

The first, it was added `cpuLimit: "100m"` to the `redhat/java8` plugin sidecar
https://gist.githubusercontent.com/vitaliy-guliy/be9be3fa4734d1d81c9f80a841027b31/raw/1e9c3d983f8ef73a8a8a35edb590a2c61fef4a38/meta.yaml

But to the workspace deployment this limitation was transferred incorrectly (`100` instead of `100m`).
```
            "resources": {
              "limits": {
                "cpu": "100",
                "memory": "1342177280"
              },
              "requests": {
                "memory": "67108864"
              }
            },
```

<details>
<summary>See full deployment here</summary>

```
{
  "kind": "Deployment",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "name": "workspace20b3s2c5dbdzmxsf.che-workspace-pod",
    "namespace": "che",
    "selfLink": "/apis/extensions/v1beta1/namespaces/che/deployments/workspace20b3s2c5dbdzmxsf.che-workspace-pod",
    "uid": "39094b4c-bad1-4a33-9d18-c387c6cfd9f7",
    "resourceVersion": "35352",
    "generation": 1,
    "creationTimestamp": "2020-12-16T16:56:57Z",
    "labels": {
      "che.workspace_id": "workspace20b3s2c5dbdzmxsf"
    },
    "annotations": {
      "deployment.kubernetes.io/revision": "1"
    }
  },
  "spec": {
    "replicas": 1,
    "selector": {
      "matchLabels": {
        "che.deployment_name": "workspace20b3s2c5dbdzmxsf.che-workspace-pod",
        "che.original_name": "che-workspace-pod",
        "che.workspace_id": "workspace20b3s2c5dbdzmxsf",
        "deployment": "workspace"
      }
    },
    "template": {
      "metadata": {
        "creationTimestamp": null,
        "labels": {
          "che.deployment_name": "workspace20b3s2c5dbdzmxsf.che-workspace-pod",
          "che.original_name": "che-workspace-pod",
          "che.workspace_id": "workspace20b3s2c5dbdzmxsf",
          "deployment": "workspace"
        },
        "annotations": {
          "org.eclipse.che.container.display-name/che-jwtproxyyp856mln": "che-jwtproxy",
          "org.eclipse.che.container.display-name/che-machine-execro4": "che-machine-execro4",
          "org.eclipse.che.container.display-name/che-plugin-artifacts-broker-v3-4-0": "che-workspace-pod/che-plugin-artifacts-broker-v3-4-0",
          "org.eclipse.che.container.display-name/remote-runtime-injector593": "che-workspace-pod/remote-runtime-injector593",
          "org.eclipse.che.container.display-name/theia-iderov": "theia-iderov",
          "org.eclipse.che.container.display-name/vscode-java36x": "vscode-java36x"
        }
      },
      "spec": {
        "volumes": [
          {
            "name": "che-jwtproxy-config-volume",
            "configMap": {
              "name": "workspace20b3s2c5dbdzmxsf.jwtproxy-config",
              "defaultMode": 420
            }
          },
          {
            "name": "remote-endpoint",
            "emptyDir": {}
          },
          {
            "name": "broker-config-volumet5z1ie",
            "configMap": {
              "name": "workspace20b3s2c5dbdzmxsf.broker-config-mapojulyj",
              "defaultMode": 420
            }
          },
          {
            "name": "claim-che-workspace",
            "persistentVolumeClaim": {
              "claimName": "claim-che-workspace"
            }
          },
          {
            "name": "che-self-signed-cert",
            "secret": {
              "secretName": "workspace20b3s2c5dbdzmxsf-che-self-signed-cert",
              "defaultMode": 420
            }
          },
          {
            "name": "workspace20b3s2c5dbdzmxsf-sshprivatekeys",
            "secret": {
              "secretName": "workspace20b3s2c5dbdzmxsf-sshprivatekeys",
              "defaultMode": 384
            }
          },
          {
            "name": "ssshkeyconfigvolume",
            "configMap": {
              "name": "workspace20b3s2c5dbdzmxsf-sshconfigmap",
              "defaultMode": 420
            }
          },
          {
            "name": "gitconfigvolume",
            "configMap": {
              "name": "workspace20b3s2c5dbdzmxsf-gitconfig",
              "defaultMode": 420
            }
          }
        ],
        "initContainers": [
          {
            "name": "remote-runtime-injector593",
            "image": "quay.io/eclipse/che-theia-endpoint-runtime-binary:7.22.2",
            "env": [
              {
                "name": "PLUGIN_REMOTE_ENDPOINT_EXECUTABLE",
                "value": "/remote-endpoint/plugin-remote-endpoint"
              },
              {
                "name": "REMOTE_ENDPOINT_VOLUME_NAME",
                "value": "remote-endpoint"
              }
            ],
            "resources": {},
            "volumeMounts": [
              {
                "name": "remote-endpoint",
                "mountPath": "/remote-endpoint"
              },
              {
                "name": "che-self-signed-cert",
                "readOnly": true,
                "mountPath": "/tmp/che/secret/"
              }
            ],
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "imagePullPolicy": "Always"
          },
          {
            "name": "che-plugin-artifacts-broker-v3-4-0",
            "image": "quay.io/eclipse/che-plugin-artifacts-broker:v3.4.0",
            "args": [
              "--push-endpoint",
              "wss://che-che.192.168.99.218.nip.io/api/websocket",
              "--runtime-id",
              "workspace20b3s2c5dbdzmxsf::87e1efd5-901a-4250-97db-78aeec9f47d9",
              "--cacert",
              "/tmp/che/secret/ca.crt",
              "--registry-address",
              "https://plugin-registry-che.192.168.99.218.nip.io/v3",
              "--metas",
              "/broker-config/config.json"
            ],
            "env": [
              {
                "name": "CHE_AUTH_ENABLED",
                "value": "true"
              },
              {
                "name": "CHE_MACHINE_TOKEN",
                "value": "eyJhbGciOiJSUzI1NiIsImtpbmQiOiJtYWNoaW5lX3Rva2VuIiwia2lkIjoid29ya3NwYWNlMjBiM3MyYzVkYmR6bXhzZiJ9.eyJ3c2lkIjoid29ya3NwYWNlMjBiM3MyYzVkYmR6bXhzZiIsInVpZCI6Ijg3ZTFlZmQ1LTkwMWEtNDI1MC05N2RiLTc4YWVlYzlmNDdkOSIsImF1ZCI6IndvcmtzcGFjZTIwYjNzMmM1ZGJkem14c2YiLCJuYmYiOi0xLCJ1bmFtZSI6ImFkbWluIiwiaXNzIjoid3NtYXN0ZXIiLCJleHAiOjE2Mzk2NzM3OTYsImlhdCI6MTYwODEzNzc5NiwianRpIjoiYmUxNzY4YmMtNjM2MS00NWJjLTg1MjEtZGVlNmQxNTcyM2UzIn0.QEpYi5P4IlfU4dr1pA6BfGqF18arAtUAGYzpFDEH15WBq0oPEUxeuqLtx_XVopI5q18GRRO0UzEw23plGahMS7Gd08ztknZGoGTajpukz7AEyXGJw8_CiWEHYawIawUdFpwkv8SwAeJVUsdNGntitRQCIaQ9VBF1gZK3qy5a9yjDeMTK3sLR176VAjzUSMf7gS5680Le29CODY-QhgD3LLQeSswh2ELTH6gmyWV6NsSWD6vF7ikHOH66ptgKRe9xFxU-8xEuEoutdFMkKVYCTSqmvKSWPlf5r9DZZPpXeJv04xpIOwdPfvjDBk13OSEFFAfOV_ASovC9suEieFhfIg"
              }
            ],
            "resources": {
              "limits": {
                "memory": "250Mi"
              },
              "requests": {
                "memory": "250Mi"
              }
            },
            "volumeMounts": [
              {
                "name": "broker-config-volumet5z1ie",
                "readOnly": true,
                "mountPath": "/broker-config/"
              },
              {
                "name": "claim-che-workspace",
                "mountPath": "/plugins",
                "subPath": "workspace20b3s2c5dbdzmxsf/plugins/"
              },
              {
                "name": "claim-che-workspace",
                "mountPath": "/workspace_logs",
                "subPath": "workspace20b3s2c5dbdzmxsf/che-logs-che-workspace-pod/"
              },
              {
                "name": "che-self-signed-cert",
                "readOnly": true,
                "mountPath": "/tmp/che/secret/"
              }
            ],
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "imagePullPolicy": "Always"
          }
        ],
        "containers": [
          {
            "name": "che-jwtproxyyp856mln",
            "image": "quay.io/eclipse/che-jwtproxy:0.10.0",
            "args": [
              "-config",
              "/che-jwtproxy-config/config.yaml"
            ],
            "env": [
              {
                "name": "XDG_CONFIG_HOME",
                "value": "/che-jwtproxy-config"
              }
            ],
            "resources": {
              "limits": {
                "cpu": "500m",
                "memory": "134217728"
              },
              "requests": {
                "memory": "134217728"
              }
            },
            "volumeMounts": [
              {
                "name": "che-jwtproxy-config-volume",
                "mountPath": "/che-jwtproxy-config/"
              },
              {
                "name": "che-self-signed-cert",
                "readOnly": true,
                "mountPath": "/tmp/che/secret/"
              },
              {
                "name": "workspace20b3s2c5dbdzmxsf-sshprivatekeys",
                "readOnly": true,
                "mountPath": "/etc/ssh/private"
              },
              {
                "name": "ssshkeyconfigvolume",
                "readOnly": true,
                "mountPath": "/etc/ssh/ssh_config",
                "subPath": "ssh_config"
              },
              {
                "name": "gitconfigvolume",
                "mountPath": "/etc/gitconfig",
                "subPath": "gitconfig"
              }
            ],
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "imagePullPolicy": "Always"
          },
          {
            "name": "vscode-java36x",
            "image": "quay.io/eclipse/che-plugin-sidecar:java8-b8f0528",
            "env": [
              {
                "name": "THEIA_PLUGINS",
                "value": "local-dir:///plugins/sidecars/redhat_java8_latest"
              },
              {
                "name": "CHE_MACHINE_TOKEN",
                "value": "eyJhbGciOiJSUzI1NiIsImtpbmQiOiJtYWNoaW5lX3Rva2VuIiwia2lkIjoid29ya3NwYWNlMjBiM3MyYzVkYmR6bXhzZiJ9.eyJ3c2lkIjoid29ya3NwYWNlMjBiM3MyYzVkYmR6bXhzZiIsInVpZCI6Ijg3ZTFlZmQ1LTkwMWEtNDI1MC05N2RiLTc4YWVlYzlmNDdkOSIsImF1ZCI6IndvcmtzcGFjZTIwYjNzMmM1ZGJkem14c2YiLCJuYmYiOi0xLCJ1bmFtZSI6ImFkbWluIiwiaXNzIjoid3NtYXN0ZXIiLCJleHAiOjE2Mzk2NzM3OTYsImlhdCI6MTYwODEzNzc5NiwianRpIjoiYmUxNzY4YmMtNjM2MS00NWJjLTg1MjEtZGVlNmQxNTcyM2UzIn0.QEpYi5P4IlfU4dr1pA6BfGqF18arAtUAGYzpFDEH15WBq0oPEUxeuqLtx_XVopI5q18GRRO0UzEw23plGahMS7Gd08ztknZGoGTajpukz7AEyXGJw8_CiWEHYawIawUdFpwkv8SwAeJVUsdNGntitRQCIaQ9VBF1gZK3qy5a9yjDeMTK3sLR176VAjzUSMf7gS5680Le29CODY-QhgD3LLQeSswh2ELTH6gmyWV6NsSWD6vF7ikHOH66ptgKRe9xFxU-8xEuEoutdFMkKVYCTSqmvKSWPlf5r9DZZPpXeJv04xpIOwdPfvjDBk13OSEFFAfOV_ASovC9suEieFhfIg"
              },
              {
                "name": "CHE_PROJECTS_ROOT",
                "value": "/projects"
              },
              {
                "name": "CHE_MACHINE_AUTH_SIGNATURE__PUBLIC__KEY",
                "value": "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjm9wvWb1wbzY1qVFgQGkWXti/0/BNgo+6yS/DWBF6PiZ88inD/oyse3G2gSznyXeq8GfAcq/kNAqBnMk64iR8ls7KQ0Ohorivn8VSgWK0JadpMk3iefSyWFuar3/zUHoMsm3V4nC30fWqIYlO8sdx7d2ijEYj+nbQ+DeXQvFT38QVlkL4gDcnVd2lUT+lymAqCEIVitUByWH3maGqGYdbnUER1Jw+5Fh1xLvcUe6goL1UwzJe1g7pCS2X01Z3XnUUKbGpI78rXoCVLoEQ+CkOPgvgyRQESxzBHisQx5aX2/EcPogEfgWr+vEChfh3/wyzX34FeJ078jC0bZesksgwwIDAQAB"
              },
              {
                "name": "CHE_API",
                "value": "https://che-che.192.168.99.218.nip.io/api"
              },
              {
                "name": "CHE_WORKSPACE_NAME",
                "value": "java-mongo-ahed5"
              },
              {
                "name": "CHE_WORKSPACE_LOGS_ROOT__DIR",
                "value": "/workspace_logs"
              },
              {
                "name": "PLUGIN_REMOTE_ENDPOINT_EXECUTABLE",
                "value": "/remote-endpoint/plugin-remote-endpoint"
              },
              {
                "name": "CHE_MACHINE_AUTH_SIGNATURE__ALGORITHM",
                "value": "RSA"
              },
              {
                "name": "CHE_WORKSPACE_NAMESPACE",
                "value": "admin"
              },
              {
                "name": "CHE_API_INTERNAL",
                "value": "https://che-che.192.168.99.218.nip.io/api"
              },
              {
                "name": "CHE_MACHINE_NAME",
                "value": "vscode-java36x"
              },
              {
                "name": "CHE_WORKSPACE_ID",
                "value": "workspace20b3s2c5dbdzmxsf"
              },
              {
                "name": "CHE_API_EXTERNAL",
                "value": "https://che-che.192.168.99.218.nip.io/api"
              }
            ],
            "resources": {
              "limits": {
                "cpu": "100",
                "memory": "1342177280"
              },
              "requests": {
                "memory": "67108864"
              }
            },
            "volumeMounts": [
              {
                "name": "claim-che-workspace",
                "mountPath": "/home/theia/.m2",
                "subPath": "workspace20b3s2c5dbdzmxsf/m2/"
              },
              {
                "name": "claim-che-workspace",
                "mountPath": "/plugins",
                "subPath": "workspace20b3s2c5dbdzmxsf/plugins/"
              },
              {
                "name": "remote-endpoint",
                "mountPath": "/remote-endpoint"
              },
              {
                "name": "claim-che-workspace",
                "mountPath": "/workspace_logs",
                "subPath": "workspace20b3s2c5dbdzmxsf/che-logs-che-workspace-pod/"
              },
              {
                "name": "claim-che-workspace",
                "mountPath": "/projects",
                "subPath": "workspace20b3s2c5dbdzmxsf/projects/"
              },
              {
                "name": "che-self-signed-cert",
                "readOnly": true,
                "mountPath": "/tmp/che/secret/"
              },
              {
                "name": "workspace20b3s2c5dbdzmxsf-sshprivatekeys",
                "readOnly": true,
                "mountPath": "/etc/ssh/private"
              },
              {
                "name": "ssshkeyconfigvolume",
                "readOnly": true,
                "mountPath": "/etc/ssh/ssh_config",
                "subPath": "ssh_config"
              },
              {
                "name": "gitconfigvolume",
                "mountPath": "/etc/gitconfig",
                "subPath": "gitconfig"
              }
            ],
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "imagePullPolicy": "Always"
          },
          {
            "name": "che-machine-execro4",
            "image": "quay.io/eclipse/che-machine-exec:7.22.2",
            "command": [
              "/go/bin/che-machine-exec",
              "--url",
              "127.0.0.1:4444"
            ],
            "ports": [
              {
                "containerPort": 4444,
                "protocol": "TCP"
              }
            ],
            "env": [
              {
                "name": "CHE_WORKSPACE_NAME",
                "value": "java-mongo-ahed5"
              },
              {
                "name": "CHE_WORKSPACE_LOGS_ROOT__DIR",
                "value": "/workspace_logs"
              },
              {
                "name": "CHE_MACHINE_TOKEN",
                "value": "eyJhbGciOiJSUzI1NiIsImtpbmQiOiJtYWNoaW5lX3Rva2VuIiwia2lkIjoid29ya3NwYWNlMjBiM3MyYzVkYmR6bXhzZiJ9.eyJ3c2lkIjoid29ya3NwYWNlMjBiM3MyYzVkYmR6bXhzZiIsInVpZCI6Ijg3ZTFlZmQ1LTkwMWEtNDI1MC05N2RiLTc4YWVlYzlmNDdkOSIsImF1ZCI6IndvcmtzcGFjZTIwYjNzMmM1ZGJkem14c2YiLCJuYmYiOi0xLCJ1bmFtZSI6ImFkbWluIiwiaXNzIjoid3NtYXN0ZXIiLCJleHAiOjE2Mzk2NzM3OTYsImlhdCI6MTYwODEzNzc5NiwianRpIjoiYmUxNzY4YmMtNjM2MS00NWJjLTg1MjEtZGVlNmQxNTcyM2UzIn0.QEpYi5P4IlfU4dr1pA6BfGqF18arAtUAGYzpFDEH15WBq0oPEUxeuqLtx_XVopI5q18GRRO0UzEw23plGahMS7Gd08ztknZGoGTajpukz7AEyXGJw8_CiWEHYawIawUdFpwkv8SwAeJVUsdNGntitRQCIaQ9VBF1gZK3qy5a9yjDeMTK3sLR176VAjzUSMf7gS5680Le29CODY-QhgD3LLQeSswh2ELTH6gmyWV6NsSWD6vF7ikHOH66ptgKRe9xFxU-8xEuEoutdFMkKVYCTSqmvKSWPlf5r9DZZPpXeJv04xpIOwdPfvjDBk13OSEFFAfOV_ASovC9suEieFhfIg"
              },
              {
                "name": "CHE_MACHINE_AUTH_SIGNATURE__ALGORITHM",
                "value": "RSA"
              },
              {
                "name": "CHE_WORKSPACE_NAMESPACE",
                "value": "admin"
              },
              {
                "name": "CHE_API_INTERNAL",
                "value": "https://che-che.192.168.99.218.nip.io/api"
              },
              {
                "name": "CHE_MACHINE_NAME",
                "value": "che-machine-execro4"
              },
              {
                "name": "CHE_WORKSPACE_ID",
                "value": "workspace20b3s2c5dbdzmxsf"
              },
              {
                "name": "CHE_PROJECTS_ROOT",
                "value": "/projects"
              },
              {
                "name": "CHE_MACHINE_AUTH_SIGNATURE__PUBLIC__KEY",
                "value": "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjm9wvWb1wbzY1qVFgQGkWXti/0/BNgo+6yS/DWBF6PiZ88inD/oyse3G2gSznyXeq8GfAcq/kNAqBnMk64iR8ls7KQ0Ohorivn8VSgWK0JadpMk3iefSyWFuar3/zUHoMsm3V4nC30fWqIYlO8sdx7d2ijEYj+nbQ+DeXQvFT38QVlkL4gDcnVd2lUT+lymAqCEIVitUByWH3maGqGYdbnUER1Jw+5Fh1xLvcUe6goL1UwzJe1g7pCS2X01Z3XnUUKbGpI78rXoCVLoEQ+CkOPgvgyRQESxzBHisQx5aX2/EcPogEfgWr+vEChfh3/wyzX34FeJ078jC0bZesksgwwIDAQAB"
              },
              {
                "name": "CHE_API",
                "value": "https://che-che.192.168.99.218.nip.io/api"
              },
              {
                "name": "CHE_API_EXTERNAL",
                "value": "https://che-che.192.168.99.218.nip.io/api"
              }
            ],
            "resources": {
              "limits": {
                "memory": "134217728"
              },
              "requests": {
                "memory": "67108864"
              }
            },
            "volumeMounts": [
              {
                "name": "claim-che-workspace",
                "mountPath": "/workspace_logs",
                "subPath": "workspace20b3s2c5dbdzmxsf/che-logs-che-workspace-pod/"
              },
              {
                "name": "che-self-signed-cert",
                "readOnly": true,
                "mountPath": "/tmp/che/secret/"
              },
              {
                "name": "workspace20b3s2c5dbdzmxsf-sshprivatekeys",
                "readOnly": true,
                "mountPath": "/etc/ssh/private"
              },
              {
                "name": "ssshkeyconfigvolume",
                "readOnly": true,
                "mountPath": "/etc/ssh/ssh_config",
                "subPath": "ssh_config"
              },
              {
                "name": "gitconfigvolume",
                "mountPath": "/etc/gitconfig",
                "subPath": "gitconfig"
              }
            ],
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "imagePullPolicy": "Always"
          },
          {
            "name": "theia-iderov",
            "image": "quay.io/eclipse/che-theia:7.22.2",
            "ports": [
              {
                "containerPort": 3100,
                "protocol": "TCP"
              },
              {
                "containerPort": 3100,
                "protocol": "TCP"
              },
              {
                "containerPort": 3100,
                "protocol": "TCP"
              },
              {
                "containerPort": 3130,
                "protocol": "TCP"
              },
              {
                "containerPort": 13131,
                "protocol": "TCP"
              },
              {
                "containerPort": 13132,
                "protocol": "TCP"
              },
              {
                "containerPort": 13133,
                "protocol": "TCP"
              }
            ],
            "env": [
              {
                "name": "THEIA_PLUGINS",
                "value": "local-dir:///plugins"
              },
              {
                "name": "CHE_MACHINE_TOKEN",
                "value": "eyJhbGciOiJSUzI1NiIsImtpbmQiOiJtYWNoaW5lX3Rva2VuIiwia2lkIjoid29ya3NwYWNlMjBiM3MyYzVkYmR6bXhzZiJ9.eyJ3c2lkIjoid29ya3NwYWNlMjBiM3MyYzVkYmR6bXhzZiIsInVpZCI6Ijg3ZTFlZmQ1LTkwMWEtNDI1MC05N2RiLTc4YWVlYzlmNDdkOSIsImF1ZCI6IndvcmtzcGFjZTIwYjNzMmM1ZGJkem14c2YiLCJuYmYiOi0xLCJ1bmFtZSI6ImFkbWluIiwiaXNzIjoid3NtYXN0ZXIiLCJleHAiOjE2Mzk2NzM3OTYsImlhdCI6MTYwODEzNzc5NiwianRpIjoiYmUxNzY4YmMtNjM2MS00NWJjLTg1MjEtZGVlNmQxNTcyM2UzIn0.QEpYi5P4IlfU4dr1pA6BfGqF18arAtUAGYzpFDEH15WBq0oPEUxeuqLtx_XVopI5q18GRRO0UzEw23plGahMS7Gd08ztknZGoGTajpukz7AEyXGJw8_CiWEHYawIawUdFpwkv8SwAeJVUsdNGntitRQCIaQ9VBF1gZK3qy5a9yjDeMTK3sLR176VAjzUSMf7gS5680Le29CODY-QhgD3LLQeSswh2ELTH6gmyWV6NsSWD6vF7ikHOH66ptgKRe9xFxU-8xEuEoutdFMkKVYCTSqmvKSWPlf5r9DZZPpXeJv04xpIOwdPfvjDBk13OSEFFAfOV_ASovC9suEieFhfIg"
              },
              {
                "name": "HOSTED_PLUGIN_PORT",
                "value": "3130"
              },
              {
                "name": "THEIA_HOST",
                "value": "127.0.0.1"
              },
              {
                "name": "CHE_PROJECTS_ROOT",
                "value": "/projects"
              },
              {
                "name": "CHE_MACHINE_AUTH_SIGNATURE__PUBLIC__KEY",
                "value": "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjm9wvWb1wbzY1qVFgQGkWXti/0/BNgo+6yS/DWBF6PiZ88inD/oyse3G2gSznyXeq8GfAcq/kNAqBnMk64iR8ls7KQ0Ohorivn8VSgWK0JadpMk3iefSyWFuar3/zUHoMsm3V4nC30fWqIYlO8sdx7d2ijEYj+nbQ+DeXQvFT38QVlkL4gDcnVd2lUT+lymAqCEIVitUByWH3maGqGYdbnUER1Jw+5Fh1xLvcUe6goL1UwzJe1g7pCS2X01Z3XnUUKbGpI78rXoCVLoEQ+CkOPgvgyRQESxzBHisQx5aX2/EcPogEfgWr+vEChfh3/wyzX34FeJ078jC0bZesksgwwIDAQAB"
              },
              {
                "name": "CHE_API",
                "value": "https://che-che.192.168.99.218.nip.io/api"
              },
              {
                "name": "CHE_WORKSPACE_NAME",
                "value": "java-mongo-ahed5"
              },
              {
                "name": "HOSTED_PLUGIN_HOSTNAME",
                "value": "0.0.0.0"
              },
              {
                "name": "CHE_WORKSPACE_LOGS_ROOT__DIR",
                "value": "/workspace_logs"
              },
              {
                "name": "CHE_MACHINE_AUTH_SIGNATURE__ALGORITHM",
                "value": "RSA"
              },
              {
                "name": "CHE_WORKSPACE_NAMESPACE",
                "value": "admin"
              },
              {
                "name": "CHE_API_INTERNAL",
                "value": "https://che-che.192.168.99.218.nip.io/api"
              },
              {
                "name": "CHE_MACHINE_NAME",
                "value": "theia-iderov"
              },
              {
                "name": "CHE_WORKSPACE_ID",
                "value": "workspace20b3s2c5dbdzmxsf"
              },
              {
                "name": "CHE_API_EXTERNAL",
                "value": "https://che-che.192.168.99.218.nip.io/api"
              }
            ],
            "resources": {
              "limits": {
                "memory": "512M"
              },
              "requests": {
                "memory": "67108864"
              }
            },
            "volumeMounts": [
              {
                "name": "claim-che-workspace",
                "mountPath": "/plugins",
                "subPath": "workspace20b3s2c5dbdzmxsf/plugins/"
              },
              {
                "name": "claim-che-workspace",
                "mountPath": "/workspace_logs",
                "subPath": "workspace20b3s2c5dbdzmxsf/che-logs-che-workspace-pod/"
              },
              {
                "name": "claim-che-workspace",
                "mountPath": "/projects",
                "subPath": "workspace20b3s2c5dbdzmxsf/projects/"
              },
              {
                "name": "che-self-signed-cert",
                "readOnly": true,
                "mountPath": "/tmp/che/secret/"
              },
              {
                "name": "workspace20b3s2c5dbdzmxsf-sshprivatekeys",
                "readOnly": true,
                "mountPath": "/etc/ssh/private"
              },
              {
                "name": "ssshkeyconfigvolume",
                "readOnly": true,
                "mountPath": "/etc/ssh/ssh_config",
                "subPath": "ssh_config"
              },
              {
                "name": "gitconfigvolume",
                "mountPath": "/etc/gitconfig",
                "subPath": "gitconfig"
              }
            ],
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "imagePullPolicy": "Always"
          }
        ],
        "restartPolicy": "Always",
        "terminationGracePeriodSeconds": 0,
        "dnsPolicy": "ClusterFirst",
        "serviceAccountName": "che-workspace",
        "serviceAccount": "che-workspace",
        "securityContext": {
          "runAsUser": 1724,
          "fsGroup": 1724
        },
        "schedulerName": "default-scheduler"
      }
    },
    "strategy": {
      "type": "RollingUpdate",
      "rollingUpdate": {
        "maxUnavailable": "25%",
        "maxSurge": "25%"
      }
    },
    "revisionHistoryLimit": 10,
    "progressDeadlineSeconds": 600
  },
  "status": {
    "observedGeneration": 1,
    "replicas": 1,
    "updatedReplicas": 1,
    "unavailableReplicas": 1,
    "conditions": [
      {
        "type": "Available",
        "status": "False",
        "lastUpdateTime": "2020-12-16T16:56:57Z",
        "lastTransitionTime": "2020-12-16T16:56:57Z",
        "reason": "MinimumReplicasUnavailable",
        "message": "Deployment does not have minimum availability."
      },
      {
        "type": "Progressing",
        "status": "True",
        "lastUpdateTime": "2020-12-16T16:56:57Z",
        "lastTransitionTime": "2020-12-16T16:56:57Z",
        "reason": "ReplicaSetUpdated",
        "message": "ReplicaSet \"workspace20b3s2c5dbdzmxsf.che-workspace-pod-7db4cb749b\" is progressing."
      }
    ]
  }
}
```

</details>

The issue is reproducible only on local minikube. On hosted Che the workspace started w/o any problems.

### Che version

 - [x] latest

### Chectl version
```
chectl/7.22.2 linux-x64 node-v10.23.0
```

### Steps to reproduce

1. Deploy Che on local minikube (tested on multiuser)
2. Create a workspace with the devfile
```
---
apiVersion: 1.0.0
metadata:
  generateName: java-mongo-
projects:
-
  name: java-guestbook
  source:
    type: git
    location: "https://github.com/che-samples/java-guestbook.git"
components:
-
  type: chePlugin
  # id: redhat/java8/latest
  memoryLimit: 1280Mi
  reference: https://gist.githubusercontent.com/vitaliy-guliy/be9be3fa4734d1d81c9f80a841027b31/raw/1e9c3d983f8ef73a8a8a35edb590a2c61fef4a38/meta.yaml
```

### Runtime
   - [x] minikube (include output of `minikube version` and `kubectl version`)

### Screenshots

![Screenshot from 2020-12-16 17-12-40](https://user-images.githubusercontent.com/1655894/102382834-8a8bd000-3fd3-11eb-81aa-f7c25665eaab.png)

![Screenshot from 2020-12-16 18-57-06](https://user-images.githubusercontent.com/1655894/102382871-924b7480-3fd3-11eb-8900-19521951ed46.png)

![Screenshot from 2020-12-16 17-13-02](https://user-images.githubusercontent.com/1655894/102382898-98415580-3fd3-11eb-8b27-b5337e74702d.png)

### Installation method
```
chectl server:deploy --platform=minikube
```

### Environment
   - [x] my computer
       - [x] Linux

**Comment by skabashnyuk** [comment]
possible duplicated of https://github.com/eclipse/che/issues/18484 that was fixed in  https://github.com/eclipse/che/pull/18527

**Comment by sparkoo** [comment]
@vitaliy-guliy can you please confirm it is still reproducible in latest version?

**Comment by vitaliy-guliy** [comment]
> @vitaliy-guliy can you please confirm it is still reproducible in latest version?

I have just tested it in latest Che on local minikube and haven't found any issues.
