### ISSUE TITLE
The "shellcheck" plugin doesn't work

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#19376]
### Describe the bug
The "shellcheck" plugin doesn't work

### Che version

 - [ ] latest
 - [ x ] nightly
 - [ ] other: please specify

### Steps to reproduce

- Create workspace using next devfile https://gist.githubusercontent.com/Ohrimenko1988/f8ea2b4ae1eada70d7072df43de22dd5/raw/d7d448a38ffd9668506f232a1eb41bdf48278d15/shellcheckPlugin.yaml
- Set prefernces "shellcheck.executablePath: /bin/shellcheck"
- Go inside created workspace and open the "test.sh" file
- Verify shellcheck features

### Expected behavior:
- Warning highlighting in the 5th row
- Warning highlighting disappeared after uncommenting 3rd line

### Observed behavior:
- Shellcheck features don't work

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ x ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ x ] chectl
```
./chectl server:deploy \
  --k8spodreadytimeout=600000 \
  --k8spodwaittimeout=600000 \
  --k8spoddownloadimagetimeout=600000 \
  --listr-renderer=verbose \
  --platform=minikube \
  --chenamespace=iokhrime-che \
  --telemetry=off
```
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ x ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

**Comment by ericwill** [comment]
I tested the latest plugin and it's working fine. It was most likely fixed by: https://github.com/eclipse-che/che-plugin-registry/pull/905

**Comment by Ohrimenko1988** [comment]
Still reproducing on my environment:

 - chectl/0.0.20210408-next.cf44212 linux-x64 node-v12.22.0
 - editor: editor - https://github.com/eclipse-che/che-theia/commit/8b7d633
 - plugin-registry image:
 
![Screenshot from 2021-04-09 15-12-09](https://user-images.githubusercontent.com/22724619/114178382-53f11100-9946-11eb-8454-a28f6adc5ac0.png)

**Comment by Ohrimenko1988** [comment]
I also configured preferences:
![Screenshot from 2021-04-09 15-08-58](https://user-images.githubusercontent.com/22724619/114178478-71be7600-9946-11eb-8d81-fa7d622d3ce1.png)

**Comment by tsmaeder** [comment]
I can reproduce the problem on the dogfooding instance against both che-theia:latest and che-theia:next, but not in a self-hosting setup.

**Comment by tsmaeder** [comment]
I noticed something weird inside the `shellcheck` sidecar: . The user is 

1. the $HOME variable points to `/`
2. The user in the shell is `user`
3. The root directory is not writeable.

All of this could very well lead to the plugin not working correctly.

**Comment by ericwill** [comment]
@tsmaeder is this issue done now?
