### ISSUE TITLE
Clone from GitHub is not possible using IDE UI

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#20316]
### Describe the bug

* _The 'Clone from GitHub' container after invoke 'Git: Clone' command is not appear in IDE_

### Che version

next (development version)

### Steps to reproduce

1. Run a workspace 
2. Go to 'View' -> 'Find Command', type 'clone'
3. Choose and click  'Git: Clone'

### Expected behavior

* The 'Clone from GitHub' pop-up should be appear after invoke 'Git: Clone'
* See screenshot:
![che-git -clone-container](https://user-images.githubusercontent.com/5408906/129735548-bb6fc603-a8ee-4460-8105-776cba1f3651.png)

### Runtime

OpenShift, minikube

### Screenshots

https://user-images.githubusercontent.com/5408906/129736841-16771636-8f25-48f7-b340-7e7671a1d20c.mp4

### Installation method

chectl/next

### Environment

Linux

**Comment by vinokurig** [comment]
Should be fixed by https://github.com/eclipse-theia/theia/pull/10055

**Comment by vinokurig** [comment]
Should be fixed by https://github.com/eclipse-theia/theia/pull/10065

**Comment by svor** [comment]
Seems https://github.com/eclipse-theia/theia/pull/10065 didn't fix the problem
@vinokurig will take a look once he gets back from PTO

**Comment by svor** [comment]
Fixed by https://github.com/eclipse-theia/theia/pull/10230 and https://github.com/eclipse/che/issues/20538

**Comment by kollachaitanyakrishna** [comment]
@artaleks9: can you confirm on how do you tested this bug. 

In my case I tried to pull the latest tag "7.41.2" for the che dashboard [(link).](https://github.com/eclipse-che/che-dashboard/tree/7.41.2) But still facing the same issue.
![Screenshot 2022-01-07 at 3 13 08 PM](https://user-images.githubusercontent.com/64516009/148524893-951ebee7-f910-4b3a-80c4-cd78836a746f.png)

**Comment by artaleks9** [comment]
@kollachaitanyakrishna
I guess you should have che-server version 7.41 or newer (not che-dashboard)..On your screenshot there is pointed 'Server Version 7.40.2.
If you return back to your closed issue #20978, there is the comment :
```
it was fixed in 7.41
```
So try use correect tag of che-server --> https://github.com/eclipse/che
