### ISSUE TITLE
che-theia fails with `redhat/java8/latest` plugin

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#20360]
### Describe the bug

It's impossible to properly start a workspace if there is `redhat/java8/latest` plugin in the devfile.
The bug is reproducible only if build che-theia, based on `eclipse-theia/theia/master`.

The problem does not depend on the infrastructure and the installation method.

### Che version

latest

### Steps to reproduce

- Build che-theia image

1. build che-theia:next image, using `eclipse-che/che-theia/main` and `eclipse-theia/theia/master`
2. create a minimal devfile, use built che-theia and latest `redhat/java8` plugin.
3. start a workspace, open browser console, check errors

You will not be able to see `My Workspace` and other views, that contributed by plugins. The most of plugins at this point are not properly started.

- Do not build anything, just run prepared devfile

```
apiVersion: 1.0.0
metadata:
  name: minimal-workspace
projects:
  - name: web-java-spring-petclinic
    source:
      location: 'https://github.com/che-samples/java-spring-petclinic'
      type: git
components:
  - type: cheEditor
    alias: che-theia
    reference: https://gist.githubusercontent.com/vitaliy-guliy/261c8e37493c20d6504701c537a146e0/raw/24606999f923183f992f34d6617f570dd7e0858c/editor.meta.yaml
  - id: redhat/java8/latest
    type: chePlugin
```

### Expected behavior

Plugin system must be working.

### Runtime

other (please specify in additional context)

### Screenshots

![Screenshot from 2021-08-25 19-38-53](https://user-images.githubusercontent.com/1655894/130836623-4a1be18b-37b7-4217-bb95-2ab9e03ba67e.png)

There are few unexpected errors, which could be reason of failure
![Screenshot from 2021-08-25 20-32-29](https://user-images.githubusercontent.com/1655894/130838173-aa14325c-5dc4-4dce-a49f-5593a31b8f5b.png)

![Screenshot from 2021-08-25 20-32-35](https://user-images.githubusercontent.com/1655894/130838192-0e1577e6-04ba-46c1-bc7b-130021ec55d1.png)

There is a similar error on che-theia backend
![Screenshot from 2021-08-25 20-45-00](https://user-images.githubusercontent.com/1655894/130839950-d64cc4cd-544a-4eb3-b365-2e0574a49383.png)

### Installation method

other (please specify in additional context)

### Environment

Dev Sandbox (workspaces.openshift.com), other (please specify in additional context)

**Comment by tsmaeder** [comment]
I can see the same behavior in the image built for https://github.com/eclipse-che/che-theia/pull/1202. So I assume this is a general problem. We need a hight priority, here.

**Comment by azatsarynnyy** [comment]
@vitaliy-guliy is it fixed by https://github.com/eclipse-che/che-theia/pull/1205?

**Comment by vitaliy-guliy** [comment]
> @vitaliy-guliy is it fixed by [eclipse-che/che-theia#1205](https://github.com/eclipse-che/che-theia/pull/1205)?

It's not fixed, but just works with that temporary fix.
I think it's better to wait a bit and check the plugin after solving https://github.com/eclipse/che/issues/20366

**Comment by RomanNikitenko** [comment]
I investigated the problem and found that:
- according to the recent changes in upstream, `theia` tries to read a `package.json` file for a `vscode` extension at starting the IDE
- the path looks like `/tmp/vscode-unpacked/redhat.java.latest.toxohserdj.java-0.75.0-60.vsix/extension/package.json` for the java extension, for example
- but `/tmp/vscode-unpacked/` doesn't exist in `theia-ide` container, it's present in `vscode-java` container instead

That's why `che-theia` fails with a vscode plugin...
I'm looking for a good solution for that problem...

**Comment by tsmaeder** [comment]
> according to the recent changes in upstream, theia tries to read a package.json file for a vscode extension at starting the IDE

Which changes are you referring to?

**Comment by RomanNikitenko** [comment]
> > according to the recent changes in upstream, theia tries to read a package.json file for a vscode extension at starting the IDE
> 
> Which changes are you referring to?

added the reference to the upstream PR in my comment above

**Comment by tsmaeder** [comment]
https://github.com/eclipse-theia/theia/pull/9538/files#diff-fafbd64dc9559cdbe8985685e261e5189a336a61cc519e85dce16169baed3334R108 looks fishy to me 🤷

**Comment by RomanNikitenko** [comment]
> https://github.com/eclipse-theia/theia/pull/9538/files#diff-fafbd64dc9559cdbe8985685e261e5189a336a61cc519e85dce16169baed3334R108 looks fishy to me 🤷

it's only the entry point to the failure, but I know exactly the row where it fails, i'm looking for how to fix it...

I think the problem is actual for `che-theia` only and related to using different containers for a vscode extension, most likely there is no a use case for the vanilla `theia`...

**Comment by RomanNikitenko** [comment]
I created the corresponding images and tested that current issue is going to be fixed by upstream PR `https://github.com/eclipse-theia/theia/pull/10087`.
But there is still another problem which I detected and raised here https://github.com/eclipse/che/issues/20366#issuecomment-909253757
So, I'm debugging that problem...

**Comment by azatsarynnyy** [comment]
It should be already fixed by https://github.com/eclipse-che/che-theia/pull/1213
