### ISSUE TITLE
Error message is not shown to user on factory resolve

### ISSUE THREAD

**Issue by mshaposhnik** [eclipse-che/che#20365]
### Describe the bug

`factory/resolve` call thrown an 400 with the error message, but it is not shown to user.

### Che version

next (development version)

### Steps to reproduce

Accepa a factory with an invalid defvile

### Expected behavior

User should be able to see the error cause.

### Runtime

minikube

### Screenshots

![image](https://user-images.githubusercontent.com/1651062/130979770-64259cc4-2e73-4e31-845f-208f158260df.png)

### Installation method

chectl/next

### Environment

Linux

**Comment by sleshchenko** [comment]
fixed in 7.36 by https://github.com/eclipse-che/che-dashboard/pull/343
and 7.37 by https://github.com/eclipse-che/che-dashboard/pull/338

**Comment by mshaposhnik** [comment]
Still doesn't seems to be fixed:
![image](https://user-images.githubusercontent.com/1651062/133237939-acd4de6b-26e0-4801-83ce-1c6fc1148a6e.png)
Error code is **500** if its make any difference..

**Comment by sleshchenko** [comment]
@mshaposhnik probably you faced it because fix in main7.37 and 7.36.x but not in the main branch.

Fix will be in ': next' tag soon. Will double check that
