### ISSUE TITLE
Add CHE_DOCKER_ALWAYS__PULL__IMAGE for run portion, not just build

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#4197]
I'd like Che not to check if there's a newer stack image on Docker Hub. However, setting CHE_DOCKER_ALWAYS__PULL__IMAGE to false in che.env does not help:

```
[DOCKER] latest: Pulling from eclipse/ubuntu_jdk8 
[DOCKER] Digest: sha256:69f514b226808be7d251442096bcc61d85dcb77f91f453e1cfe090a8f350c854 
[DOCKER] Status: Image is up to date for eclipse/ubuntu_jdk8:latest 
```

This makes it impossible to use Che in a purely offline mode.

**Comment by ghost** [comment]
Blocker for Artik. Offline mode is impossible.

**Comment by TylerJewell** [comment]
Is the `che.property` value (or alias) `che.docker.always_pull_image`?  If yes, have you tried `machine.docker.pull_image` as well?  There is some code in the core Server that assigns both values to be the same, so I wonder if this alternative version works.

https://github.com/eclipse/che/blob/9370327d4606f98a904c09a45fe9923aa6df5684/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che_aliases.properties#L49

**Comment by ghost** [comment]
That did not work either

**Comment by ghost** [comment]
It turns out this is not a bug but an enhancement request.

CHE_DOCKER_ALWAYS__PULL__IMAGE works only for build, not run.

**Comment by bmicklea** [comment]
Increasing severity as this prevents true offline mode

**Comment by mmorhun** [comment]
Done

**Comment by zanoubia** [comment]
Still having the same problem, I think, with codenvy offline mode.
Although I already downloaded the stacks I need, I can't run workspaces

# docker images
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
.
.
eclipse/centos_jdk8   latest              5bd02d36ed35        5 weeks ago         877MB

And I have the following logs in instance/logs/codenvy/che-machines-logs/machineuswhc5e31bn9wnzm/machineId.logs

[DOCKER] Step 1/1 : FROM eclipse/centos_jdk8
[DOCKER]
[DOCKER] [ERROR] Failed to build image: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on  <>:53: no such host
[ERROR] Docker image build failed. Image id not found in build output.

**Comment by mmorhun** [comment]
I would recommend you to specify the version you are using in such cases.
Just checked with nightly Che build - everything works as expected.
(I created image for workspace and didn't push it. Workspace started from it without a problem.)
Just for case, the property takes effect after Che restart.

**Comment by zanoubia** [comment]
CODENVY_VERSION:    5.22.2

**Comment by eivantsov** [comment]
@zanoubia this is Eclipse Che repository. Please, give it a try with the latest Che release.

**Comment by zanoubia** [comment]
Codenvy builds upon Eclipse Che -_-

**Comment by eivantsov** [comment]
@zanoubia Current Che version is 6.9.0-SNAPSHOT. Can you reproduce it with this version?
