### ISSUE TITLE
Regression: JSON intellisense is broken

### ISSUE THREAD

**Issue by kaloyan-raev** [eclipse-che/che#5311]
The intellisense in the JSON editor seriously regressed recently. Currently, only the basic syntax validation works. Code completion does not work at all. Intellisense that is based on the JSON schema does not work too: validation according to the schema, hover support, etc.

It seems that the issues were caused by #4765.

There used to by a [JsonLanguageServer](https://github.com/eclipse/che/commit/fbac7eaacca9ad2f1b52023a89591a27245e2453#diff-b94078605d604c994b0a1df22d8ddd6c) class that sends schema associations to the language server, but it was simply deleted without anything replacing its functionality.

While debugging the code completion issue I found that the TextDocumentService get this exception:
```
java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request textDocument/completion failed with message: Cannot read property 'getText' of undefined
```

Opening the JSON editor also produces an error in the dev-machine output:
```
[STDOUT] java.lang.NullPointerException: null
[STDOUT] 	at org.eclipse.che.api.languageserver.messager.PublishDiagnosticsParamsJsonRpcTransmitter.lambda$subscribe$1(PublishDiagnosticsParamsJsonRpcTransmitter.java:34)
[STDOUT] 	at org.eclipse.che.api.core.notification.EventService.publish(EventService.java:106)
[STDOUT] 	at org.eclipse.che.api.languageserver.registry.ServerInitializerImpl$1.publishDiagnostics(ServerInitializerImpl.java:83)
[STDOUT] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[STDOUT] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[STDOUT] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[STDOUT] 	at java.lang.reflect.Method.invoke(Method.java:498)
[STDOUT] 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:49)
[STDOUT] 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:104)
[STDOUT] 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:164)
[STDOUT] 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:135)
[STDOUT] 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:149)
[STDOUT] 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77)
[STDOUT] 	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:68)
[STDOUT] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[STDOUT] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[STDOUT] 	at java.lang.Thread.run(Thread.java:745)
```

**Reproduction Steps:**

1. Follow the PHP tutorial
1. Try to use code completion in `composer.json` - it won't work at all.
1. Try to add a key that don't exist in the composer.json schema - no validation will be done.

**OS and version:**    Fedora 24

**Diagnostics:** 

CLI:
 TTY:            true
 Daemon:         /var/run/docker.sock
 Image:          eclipse/che:5.11.2
 Version:        5.11.2
 Command:        info
 Parameters:     info
Mounts:
 /data:          /home/kraev/Work/che-data
 /data/instance: not set
 /data/backup:   not set
 /repo:          not set
 /assembly:      /home/kraev/git/che/assembly/assembly-main/target/eclipse-che-5.12.0-SNAPSHOT/eclipse-che-5.12.0-SNAPSHOT
 /sync:          not set
 /unison:        not set
 /chedir:        not set
System:
 Docker:         native
 Proxy:          not set
Internal:
 CHE_VERSION:    5.11.2
 CHE_HOST:       172.17.0.1
 CHE_INSTANCE:   /home/kraev/Work/che-data/instance
 CHE_CONFIG:     /home/kraev/Work/che-data
 CHE_BACKUP:     /home/kraev/Work/che-data/backup
 CHE_REGISTRY:   /version
 CHE_DEBUG:      false
 IP Detection:   172.17.0.1
 Initialized:    true
Image Registry:
 IMAGE_INIT=eclipse/che-init:5.11.2
 IMAGE_CHE=eclipse/che-server:5.11.2
 IMAGE_COMPOSE=docker/compose:1.8.1
 IMAGE_TRAEFIK=traefik:v1.3.0-rc1
 BOOTSTRAP_IMAGE_ALPINE=alpine:3.4
 BOOTSTRAP_IMAGE_CHEIP=eclipse/che-ip:5.11.2
 UTILITY_IMAGE_CHEACTION=eclipse/che-action:5.11.2
 UTILITY_IMAGE_CHEDIR=eclipse/che-dir:5.11.2
 UTILITY_IMAGE_CHETEST=eclipse/che-test:5.11.2
 UTILITY_IMAGE_CHEMOUNT=eclipse/che-mount:5.11.2
che.env:
 CHE_HOST=172.17.0.1
 CHE_SINGLE_PORT=false

**Comment by kaloyan-raev** [comment]
I created PR #5324 to update the JSON language server to a newer version. It resolves only some of the issue, but is a mandatory first step in resolving this issue, because the current aging version is implemented for an older version of the protocol.

Issues that still remain:
- schema associations (#2471) are not sent to the language server.
- code completion still does not work (even after adding `$schema` key)
- schema validation is problematic (after adding `$schema` key). Validation markers appear just for a second and then disappear.

**Comment by slemeur** [comment]
@vparfonov + @evidolob : Please update on the work you did on your side + assign the proper labels on the issue. tks

**Comment by kaloyan-raev** [comment]
@evidolob I pulled from master, made a local build (`mvn clean verify -Pfast`), and started a new PHP workspace. Now the JSON language server fails to start. I found that the `/home/user/che/ls-json/launch.sh` file has this content:
```
nodejs /home/user/che/ls-json/vscode-json-server/server.js
```
instead of the expected:
```
nodejs /home/user/che/ls-json/vscode-json-server/out/jsonServerMain.js --stdio
```
What do I miss?

**Comment by evidolob** [comment]
@kaloyan-raev I not sure, I merged your pull, now in master https://github.com/eclipse/che/blob/master/agents/ls-json/src/main/resources/org.eclipse.che.ls.json.script.sh#L157 so it's should work wright.

Try to create new workspace and test on it.

**Comment by kaloyan-raev** [comment]
@evidolob I pulled and rebuilt once again and the language server now starts fine. Perhaps, I missed some step in my previous attempt.

However, I still see this issue: "Validation markers appear just for a second and then disappear."

To reproduce:
1. Have a composer.json file with this content
```json
{
	"require-dev": {
	   "phpunit/phpunit": "^6.1"
	}
}
```
2. Type something - even just a space char would be enough.
3. A warning validation (about missing "name" and "description" keys) appears on the top left of the editor.
4. After a second the warning disappears.

This only happens for the warnings related to the schema validation. It does not affect the syntax error messages.

Can you reproduce this?

**Comment by evidolob** [comment]
@kaloyan-raev Yes I can. I go to investigate this.

**Comment by evidolob** [comment]
@kaloyan-raev It's seems that Orion editor override diagnostic annotation with built in JSON validator annotations, so now I try to figure out how to disable built in JSON validator.
