### ISSUE TITLE
The C# language server does not initialize properly

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#5738]
**Reproduction Steps:**
1. Create a  workspace based on .NET stack
2. Create ASP project from wizard, open Program.cs

**Expected result:** the language server should be initialized. Code validation should work

**Actual result:** the language server does not start. 

![selection_005](https://user-images.githubusercontent.com/1640058/28361248-de71d126-6c80-11e7-974d-ca8de152c294.png)
**OS and version:**   Ubuntu 16.04

**Comment by ghost** [comment]
The problem is with dotnet in the image. Investigating.

**Comment by riuvshin** [comment]
fixed by https://github.com/eclipse/che-dockerfiles/issues/110

**Comment by ghost** [comment]
So, the problem is the following: https://github.com/dotnet/coreclr/issues/6016

Should be ok in newer .net versions.

The fix is to add `ENV COMPlus_INTERNAL_ThreadSuspendInjection=0` to a recipe. This may however slow down process start time.

It should also fix https://github.com/eclipse/che/issues/5201

.net image updated. The issue cannot be reproduced now,

**Comment by thyeun** [comment]
@eivantsov, currently i'm using Che v5.19.0, i still having the initialize issue on asp.net, as you can see from the below picture.

![selection_036](https://user-images.githubusercontent.com/1939446/31902225-b0c0080c-b856-11e7-9f98-d45018851399.jpg)

**Comment by ghost** [comment]
Are you using dotnet 2 project?

**Comment by thyeun** [comment]
@eivantsov, yes

**Comment by ghost** [comment]
Looks like it's 1.1 version. C# ls is compatible with 2.0 projects only. Can you give it a try with this sample? https://github.com/che-samples/dotnet-web-simple

**Comment by thyeun** [comment]
@eivantsov i found the error, if using command line to create a new project, than everything look good, but still have some error (not my error issue).

But if you using the "create project" with the build on "sample" (aspnet-web-simple), than it will create my error...

**Comment by thyeun** [comment]
@eivantsov, https://github.com/che-samples/dotnet-web-simple , same error, as you can see from the picture below

![selection_038](https://user-images.githubusercontent.com/1939446/31910288-96210e7e-b86f-11e7-9662-90ecdd895176.jpg)

**Comment by AndrienkoAleksandr** [comment]
@thyeun Could you do "dotnet --version", please? It's a really 2.0? What is operation system version?

**Comment by thyeun** [comment]
@AndrienkoAleksandr, dotnet --version 2.0, nothing wrong with that, just initialize still having problem

**Comment by thyeun** [comment]
@eivantsov and @AndrienkoAleksandr below is the picture i get with nothing come out and the version checking.

![selection_039](https://user-images.githubusercontent.com/1939446/31922853-01bdb6f2-b8aa-11e7-858a-1e12bf1b7340.jpg)

![selection_040](https://user-images.githubusercontent.com/1939446/31922860-0a58d53a-b8aa-11e7-936f-f2f3fa039c32.jpg)

**Comment by thyeun** [comment]
don't tell me again, this error happen to me because i'm upgrade from v5.18.0 to v5.19.0 again. i'm been having the same answer many times from previous version upgrade, but why only happen now?

**Comment by ghost** [comment]
SSL error...are you behind a proxy?

**Comment by thyeun** [comment]
@eivantsov, not using proxy, and i do not know why that error come out also? 

One things for sure, it is happen again, with fresh installation v5.19.0, no issue and initialize are prefect. Been done a fresh installation on another laptop, and the result is perfect.

i'm really kaBOOM, wasted more than a 10 hours, and it is only need a fresh installation. @.@

**Comment by ghost** [comment]
@thyeun for some reason libs that the project requires were unavailable. I don't know why. A lot of things in language server stuff are network related.

**Comment by thyeun** [comment]
@eivantsov , now my upgrade version of laptop are initialize perfect with some deletion, i got two docker/compose version before that, 1.8.x and 1.10.1, after deleted 1.8.x, and restart again, the initialize are perfect without any error. @.@ i can not believe it is related!!!!!
